### ISSUE TITLE
Custom objects - initial version

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#1017]
### What kind of idea is it?

New page on SuperOfficeDocs

### Who is it for?

User (Learn), Administrator, Consultant, Developer

### Which area (SuperOffice entity) is this related to?

Other

### Description

- [x] #1031

**Comment by kronicz** [comment]
* Include info how to main data in Custom object tables (Create, Edit, Delete) (Rewrite from old help https://help-sod.superoffice.com/Documentation/Help/EN/CRM/10.1/UserHelp/index.htm#t=Service%2Ftopics%2Fticket.listExtraTables.html%23EditEntries)

**Comment by digitaldiina** [comment]
- [ ] https://community.superoffice.com/en/product-releases/pilot-programs/current-pilot-programs/custom-objects/
- [ ] Find/show all custom objects (10.3.7)
- [ ] Triggers on load custom object (10.3.8)
- [ ] SCIL-Component to show an item from extratable (10.3.8)
