### ISSUE TITLE
Feedback for Global preferences

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#1021]
Link to mirroring where we explain exclude tables and batch size 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-admin-global-preferences](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/admin/preferences/learn/global-preferences/system.md/#L1)

**Comment by digitaldiina** [comment]
Link source: text Data mirroring in the list
Link target: mirroring-task.md#options

Add a bi-directional link. Remember that the global preferences are translated, but the mirroring section is not.
