### ISSUE TITLE
Feedback for POST TicketMessage

### ISSUE THREAD

**Issue by Anderhv** [SuperOfficeDocs/superoffice-docs#1059]
We recently upgraded to version 10.2.5, and are no longer able to set `CreatedBy` through `POST /api/v1/TicketMessage`. The following body worked before, and seems to follow the "documented" request body:

```json
{
    "Ticket": { "Ticketid": 123456 },
    "CreatedBy": { "AssociateId": 100 },
    "HtmlBody": "This is a test"
}

```

This body used to set `CreatedBy` to the `EJ_USER.Id` related to the `AssociateId`, but after the upgrade only sets to `0`. 

Has there been a breaking change here in the last few versions? If so, why is it not documented? 

Through some digging we found:
![image](https://github.com/SuperOfficeDocs/feedback/assets/25056075/1a5d9d2e-8ff1-46d5-b86d-ab45eae5ed44)
(https://docs.superoffice.com/release-notes/database/changes-10.3.1.html) - without further explanation. This is also on a later version that our current. We have made many attempts to adjust the request body, without luck. As unknown properties are simply ignored in the API, it is hard to tell where the error lies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [v1TicketMessageEntity_HttpPostSaveTicketMessageEntityWithNotify](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/api/reference/restful/rest/TicketMessage/v1TicketMessageEntity_HttpPostSaveTicketMessageEntityWithNotify.md/#L1)

**Comment by acdavidh** [comment]
@Anderhv back in 2022 it was [announced ](https://community.superoffice.com/en/technical/forums/general-forums/announcements/locking-down-registeredupdated-and-registeredassociateupdatedassociate/) that changes would be made to the Registered/Updated properties (or in case of service entities, CreatedAt/CreatedBy), they aren't supposed to be changeable.
