### ISSUE TITLE
Feedback for Deploy WebTools

### ISSUE THREAD

**Issue by superd1984** [SuperOfficeDocs/superoffice-docs#1061]
The part of the article "Supporting groups that should (not) have MailLink" is confusing. In order to have access to Mail Link should the registry entries be removed or should they stay in registry. Please make a clear formulation e.g.: 
If access needed, please delete following entries....
If  no access needed, please remove following entries....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [deploy_maillink_webextensions_on_citrix](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/onsite/install/server/ml-on-citrix.md/#L1)

**Comment by digitaldiina** [comment]
Can you please look at this @pavlas77 ?
