### ISSUE TITLE
Feedback for Servicemejl

### ISSUE THREAD

**Issue by GustafCullin** [SuperOfficeDocs/superoffice-docs#1063]
When standing here:
https://docs.superoffice.com/sv/email/service/learn/index.html

And clicking on Brevådor (email boxes) the links leads wrong.
It should lead to the chapter wher you add new emailboxes: https://docs.superoffice.com/sv/email/service/learn/screen/index.html

But instead it lead to a misleading chapter which should be removed in new service since it does not support it.
https://docs.superoffice.com/sv/email/service/learn/kb-aliases/index.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-sv-email-service](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/sv/email/service/learn/index.md/#L1)

**Comment by digitaldiina** [comment]
@GustafCullin I've updated the link in all translations (pending publication).

kb-aliases are still used by many onsite installations - and some online tenants.

Further, you *can* reach the **E-mail addresses** screen from the hamburger menu when using new service. You *can* add, update, and delete addresses - although, they have *no practical use in new service - yet*. I agree this can be confusing.

![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/23242792/4268ca4e-ac77-4d99-91f9-9b005c8db918)
