### ISSUE TITLE
Feedback for SuperOffice Docs

### ISSUE THREAD

**Issue by samuelholmstroem** [SuperOfficeDocs/superoffice-docs#1070]
Search of in docs are broken. 

![image](https://github.com/SuperOfficeDocs/feedback/assets/110456561/f60133e2-b47e-483e-8aec-a96d375b34c8)

Strange that you get a 404 error, when you are searching in docs.. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [SuperOffice Docs](https://docs.superoffice.com)

**Comment by digitaldiina** [comment]
Hi @samuelholmstroem. Unfortunately, the search index and redirects were out of sync for a while. At the moment, search appears to be working as expected and I can no longer reproduce the issue.

I've added this scenario to my release checklist. Please don't hesitate to reach out if you encounter further problems with the site  ☺.
