### ISSUE TITLE
Feedback for Markdown guide for docs.superoffice.com

### ISSUE THREAD

**Issue by ejfasting** [SuperOfficeDocs/superoffice-docs#1076]
Wrong specification for include:
[!INCLUDE [<title>](<filepath>)]

Should be:
[!INCLUDE [''](<filepath><filename>)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [markdown-guide-to-docfx](https://github.com/SuperOfficeDocs/contribution/blob/main/markdown-guide/index.md/#L1)

**Comment by digitaldiina** [comment]
Already fixed
