### ISSUE TITLE
Feedback for Template variables

### ISSUE THREAD

**Issue by PetraSimon7586** [SuperOfficeDocs/superoffice-docs#1077]
[Enter feedback here]

It is hard to find the list of document variable 

I search for Template variables, variables company card 

This could be improved
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-template-variables](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/document/learn/template-variables.md/#L1)

**Comment by digitaldiina** [comment]
@PetraSimon7586 We've grouped info about document templates and template variables into a [new section under "document"](https://docs.superoffice.com/en/document/templates/learn/index.html). You'll see the reference in all languages, however, the tables themselves are not translated. We've also added more keywords to boost the search. Hope this helps :)
