### ISSUE TITLE
Add template support for "pilot" or "preliminary documentation" notice

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/superoffice-docs#1091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of idea is it?

Look and feel

### Description

Editors should be able to either 1) add frontmatter that automatically includes a "Preliminary Documentation" warning at the top of the page or, 2) inline an include that adds a "Preliminary Documentation" warning in an article. 

```markdown
---
pilot: true|false
---
```

The pilot variable could be used to determine whether to rendered a notice at the top of pages containing Pilot (Beta) content.

This would automatically add an [include] from a top-level include file that contains a ![WARN] statement that conveys the message the content is not final and subject to change.

**Comment by digitaldiina** [comment]
See https://github.com/SuperOfficeDocs/build-docs/pull/102
