### ISSUE TITLE
Feedback for Migration guide

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#1101]
Please document that if you do a name change of your license after the migration tool has been generated, that you get the following error;

ApplicationException: Error: Unable to resume migration session because company name or serialnumber has changed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [sharepoint-documents-migration-steps](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/document/cloud/sharepoint-documents/migrate/steps.md/#L1)

**Comment by digitaldiina** [comment]
Excellent observation @acdavidh !

**Comment by acdavidh** [comment]
I just noticed this feedback is on the wrong page, should be for this one:

https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/online/migrate/index.md

**Comment by digitaldiina** [comment]
@acdavidh do you think it should go under the wizard section or requirements? Initially, I placed it in the caution on top of the step page. 

Btw I've also added a section for this exception on the troubleshooting page.

**Comment by acdavidh** [comment]
@digitaldiina I would add it under the requirements like 'Make sure no name change or serial number is performed while a migration process (either test or production) is active' (or similar)

**Comment by acdavidh** [comment]
@digitaldiina Do note you added this info to the sharepoint migration documentation, not the SuperOffice OnSite to SupoerOffice Online documentation migration. (that was what I meant with my comment earlier today that I included the wrong page for this feedback)

**Comment by digitaldiina** [comment]
@acdavidh gah, I was still in the SharePoint head-space and caught only "migrate/index" without reading the full path. My bad😳.

**Comment by acdavidh** [comment]
@digitaldiina Yes, much better 😀

Only minor would be that you could read the 'while OMT is running' part as that it is safe to do in between runs, which it is not (which we found out the hard way 😅)

So for example if you first run the OMT for a test migration, and say a few months later run it again for the final/production migration, you can't change the license name or serial number between those 2 runs.
