### ISSUE TITLE
Feedback for Running a query

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#1109]
Not sure if it was documented like this on purpose, but the documentation says that 'bypassNetServer' is not available in Online, which is not correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [search_engine_run](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/automation/crmscript/searchengine/se-run.md/#L1)

**Comment by digitaldiina** [comment]
Hi again @acdavidh, and good guess. This statement is indeed intentional. Adding "out of the box" would be more accurate, but let's not do down that rabbit hole🤫
