### ISSUE TITLE
Feedback for How to create contact

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#1116]
Issue fixed so this will work again from 10.3.2(?) - remove obsolete from title?
![image](https://github.com/SuperOfficeDocs/feedback/assets/22498774/3957f1b7-8b39-42b6-8ab2-573ed291b9e1)

See https://community.superoffice.com/en/product-releases/bugs-wishes/product-issue/?bid=54066&azure=1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [sop_create_contact](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/ui/soprotocol/create-contact.md/#L1)

**Comment by digitaldiina** [comment]
Planned for 10.3.4, don't update docs yet
