### ISSUE TITLE
Feedback for DevPortal FAQ landing page

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/superoffice-docs#1137]
Let's build a better landing page for FAQ, something like a page index with listing of subpages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [dp-format-text](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/developer-portal/faq/format-text.md/#L1)

**Comment by digitaldiina** [comment]
I'm closing this as solved by commit [ffabc14](https://github.com/SuperOfficeDocs/superoffice-docs/commit/ffabc1433d3f30ef9153db0bae7ea0ca9274a863)

If, however, there's more to do here @SuperOfficeDevNet, please reopen and specify what you have in mind :)
