### ISSUE TITLE
Feedback for GET List/Task/Headings

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/superoffice-docs#1143]
This API page appears in search, but doesn't appear in the menu anywhere... Why not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [v1TaskList_GetTaskListItemHeadings](https://github.com/SuperOfficeDocs/superoffice-docs/docs/blob/main/en/api/reference/restful/rest/List_Task/v1TaskList_GetTaskListItemHeadings.md/#L1)

**Comment by digitaldiina** [comment]
Docs are correct. The cause is the lower-case URL we get back from our search provider.
