### ISSUE TITLE
Feedback for Screen designer

### ISSUE THREAD

**Issue by samuelholmstroem** [SuperOfficeDocs/superoffice-docs#1155]
We can maybe add some information that you will need a user role with functional right  "Field administrator" to see the screen designer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-screen-designer](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/ui/screen-designer/learn/index.md/#L1)

**Comment by digitaldiina** [comment]
Suggest bundling this with #1209
