### ISSUE TITLE
Feedback for Marketing automation - flows

### ISSUE THREAD

**Issue by smedbrat** [SuperOfficeDocs/superoffice-docs#1179]
1) Success criteria: Had chat will not be prioritized for implementation unless we get user feedback of the need. Can be removed from doc.
2) We had to rewrite, SQLServer 2016 is no longer a requirement and can be removed:
https://docs.superoffice.com/en/marketing/flows/learn/index.html#requirements
SQLServer 2016 or newer - to define actions based on form submission data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-flows](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/marketing/flows/learn/index.md/#L1)

**Comment by digitaldiina** [comment]
- [ ] Retake trigger-form-submitted.png
