### ISSUE TITLE
nameWithType missing in some CRMScript class references

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#1200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which content section have you found a bug in?

CRMScript

### What kind of bug is it?

Missing info

### What happened?

During TypeScript validation, I detected multiple occurrences where `nameWithType` was blank in Native and Global reference files.

### Anything else?

Use global search in the crmscript/reference folder to find them

**Comment by SuperOfficeDevNet** [comment]
More context:

![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/15157161/d401fe97-be93-4a13-b5d6-33ff4174c484)
