### ISSUE TITLE
Screen Designer terminology column > layout

### ISSUE THREAD

**Issue by kronicz** [SuperOfficeDocs/superoffice-docs#1209]
Need to update to indicate new naming from "Columns" to "Tab layout"
<img width="178" alt="image" src="https://github.com/SuperOfficeDocs/feedback/assets/8218051/efae430a-9ab8-497b-832d-9b6ca1139dcf">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-screen-designer-edit-layout](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/ui/screen-designer/learn/edit-layout.md/#L1)

**Comment by digitaldiina** [comment]
**NOTE:** To preserve links, don't change the anchor `#columns`!
