### ISSUE TITLE
Feedback for Address formats for different countries

### ISSUE THREAD

**Issue by GerardVDC** [SuperOfficeDocs/superoffice-docs#1276]
This article mentions that there are eight different address formats. There are however 16.
Australian, Canadian, Caribbean, Denmark, European, European no postprefix, German, German small, German with title, Japanese, Netherlands, Other, Spain, United Kingdom, United States, and United States street an postal.

Recommendation is to either mention all 16 address formats, or change the text to something like "there are different address formats available" in order not to need to make changes again to the documentation when additional address formats are added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-address-formats-for-different-countries](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/company/learn/address-formats.md/#L1)

**Comment by digitaldiina** [comment]
- rephrase intro
- move UK so it's before "rest of Europe"
- remember to update translations as well
