### ISSUE TITLE
Feedback for Class SearchEngine 

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#1286]
The 'OperatorNotIn' comparison operator is not documented/missing

https://docs.superoffice.com/en/automation/crmscript/reference/CRMScript.Native.SearchEngine.html#CRMScript_Native_SearchEngine_addCriteria_String_String_String_

**Comment by SuperOfficeDevNet** [comment]
Fixed in PR #1285 https://github.com/SuperOfficeDocs/superoffice-docs/pull/1285
