### ISSUE TITLE
Feedback for Create new mailing

### ISSUE THREAD

**Issue by FBSOLT** [SuperOfficeDocs/superoffice-docs#1388]
[Feedback for this page: (There is no feedback button on this page): https://docs.superoffice.com/en/marketing/mailing/learn/create/tutorial-email-mailing.html#step-1
Include the following info: If an email is written in the "From name" issues with receiving in spam folder can occur due to SPF / DKIM / DMARC.
![image](https://github.com/user-attachments/assets/f52ab085-317b-4ab6-89bb-6da967bd2202)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-mailing-create](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/marketing/mailing/learn/create/index.md/#L1)

**Comment by digitaldiina** [comment]
We have a very similar phrasing for email settings for form response mailings, including the note about SPF look-up. Should we include the suggested info in both pages @FBSOLT ?

**Comment by FBSOLT** [comment]
Hi DigitalDiina, 
We have now tested. When e-mail is added to "From Name" - the e-mail goes to spam.
When a non e-mail is added it goes to inbox.
We could maybe advice not to put in a e-mail. It also looks weird with "e-mail address <e-mail address>" in Outlook.
