### ISSUE TITLE
Add new section for Mobile CRM to Preferences and add a new preference

### ISSUE THREAD

**Issue by pavlas77** [SuperOfficeDocs/superoffice-docs#150]
There will be a new global preference added to netserver to disable CRMScripts in Mobile CRM.

Section: Mobile CRM
Name: Enable CRMScripts

Default value will be true. Turning it off will stop Mobile from running CRMScript during save events.

**Comment by pavlas77** [comment]
Check if there are any other existing preferences for Mobile CRM - we dont have this section yet.

**Comment by pavlas77** [comment]
Yes, there are two more. Auto logout, that will automatically log out a user after x minutes the app has been in the background. Then there is Disable autologin, that will prevent on site users from enabling autologin.


Both are default off/not enabled.


So Auto logout is type number, and defuslt is 0. And Disable autologin is boolean.

**Comment by digitaldiina** [comment]
@pavlas77 which version of SuperOffice and Mobile does this section become available?

**Comment by pavlas77** [comment]
@digitaldiina The Pocket Tasks section has been there for a long time, just never documented. The Enable CRM Scripts preference is since 10,0,3,
