### ISSUE TITLE
Feedback for Request priorities

### ISSUE THREAD

**Issue by samuelholmstroem** [SuperOfficeDocs/superoffice-docs#1561]
We need to change the order of "The mailbox" and the "An email filter" in the list in this section 

_The priority assigned to a case can be determined by, for example:

The contact
The company
The mailbox
An email filter_

As the e-mail filter will apply over the e-mail box priority from the e-mail box. 

The right order should be:

The contact
The company
An email filter
The mailbox

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-request-priority](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/request/learn/priority/index.md/#L1)

**Comment by digitaldiina** [comment]
Checked with team (Stian): email filter goes on the top
