### ISSUE TITLE
Feedback for Install - online

### ISSUE THREAD

**Issue by LinaPaul** [SuperOfficeDocs/superoffice-docs#157]
[The Screenshot for the Onsite Version configuration is still pointing to Online]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [install_pocket_online](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/mobile/pocket-crm/install.md/#L1)

**Comment by digitaldiina** [comment]
- img3 (media/1v.jpg ) is incorrectly used for both online and onsite. Need a separate image for onsite (or remove the image reference).
- img4 is missing altogether. Please add the appropriate image.
