### ISSUE TITLE
Feedback for User provisioning

### ISSUE THREAD

**Issue by olegd-superoffice** [SuperOfficeDocs/superoffice-docs#1606]
There's no documentation about what happens when user is being deleted by upstream source (Entra ID) or user license is set to `(No Selection)` by rules. The customers often have questions about that.

1. When user license is set to `(No Selection)` by rules we remove the user's license and set both "IsPersonRetired" and "Deleted" flags,
2. When a user is deleted from Microsoft Entra ID: [After you delete a user, the account remains in a suspended state for 30 days](https://learn.microsoft.com/en-us/entra/fundamentals/users-restore). When this happens Entra ID sends update on the user to our SCIM API which sets "active" property on the user to "false".  For these users SCIM sets license to `(No Selection)` no matter what license is assigned by matching rules.
3. After 30 days user is deleted in Entra ID and it sends DELETE command to SCIM API. When this happens SCIM API executes NetServer's `DeleteUser` API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [user_provisioning](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/identity-management/scim/user-provisioning.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Commited update.
