### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#179]
### WHY

In essence, we currently build a fake monorepo with submodules...

* reduces overhead from managing dependencies and cross-repo changes -> more atomic commits and PRs
* makes refactoring trivial
* gets rid of (most) submodules
* gets rid of broken links caused by unavailable repos (so you can discover and fix those that are actually broken)
* encourages visibility and shared responsibility
* removes the need to maintain multiple .vscode (snippets and cspell), blueprint-templates, includes, ...
* simplifies tools, which no longer have to understand relationships between repositories
* preserves history previously broken when moving a file from repo A to repo B
* easier to work with GitHub projects and boards without having to create umbrella projects -> easier to prioritize backlog
* enables consolidation of general topics such as cusom fields and business-object content such as superoffice/docs/sale, data-access/docs/sales, crmscript/docs/sale

It will take longer to clone superoffice-docs. However, it saves you from a lot of headache jugling submodules.
The dev build-time is now so low that you gain only seconds by building a single polyrepo.

The current repos don't represent individual projects/products with their own version info. Going monorepo has no effect on this.

### HOWTO

Assumes you are on main on all involved content repos

Pre-requisites: install git filter-repo tool (https://github.com/newren/git-filter-repo) unless this is included in the client

```
cd R1
git filter-repo --to-subdirectory-filter R1
cd ../superoffice-docs
git remote add -f R1 ../R1
git merge --allow-unrelated-histories R1/main
git remote remove R1
```

Then prune and reorg the grafted files.

The database repo is similar in complexity to user-interface. crmscript and data-access will require some more post-graft moving of files and folders.

### DETAILED STEPS FOR EACH REPO

After moving the docs folder of each repo, all paths are assumed to be relative to this new location unless prefixed with repo name.
You can then also ignore the remaining files and folders in the old repo.

#### UI repo in detail

1. user-interface/docs/ > superoffice-docs/docs/ui/
2. Replace toc.yml with 00-custom/toc.yml. Remove ../ prefixes.
3. Move assets/downloads/* to superoffice-docs/docs/assets/downloads/ui/*
4. Delete includes/default-index.md
5. Rename folder service-ui to blogic
6. Rename folder web-application to web-app

#### database repo in detail

1. database/docs/ > superoffice-docs/docs/database/
2. Replace toc.yml with 00-custom/toc.yml. Remove ../ prefixes.
3. whats-new/ > superoffice-docs/release-notes/database/. Move the corresponding items from toc.yml to superoffice-docs/release-notes/toc.yml
4. Delete includes/default-index.md

#### superoffice-docs in detail

1. Replace toc.yml with 00-custom/toc.yml. Remove ../ prefixes.
2. Delete folders chat, dashboards, environment, import-export, system-design.
3. Move folder privacy into security.
4. Move folder reply-templates into service.
5. Move folder customer-center into service.
6. Move (unused) folder knowledge-base into service.
7. Move folder license into admin.
8. Move automation/trigger-scripts/ to automation/trigger/reference/
9. Update tocs to reflect the above moves.
10. Create folder howto in folders company, contact, diary, document, project, quote, sale.
11. Rename folder custom-fields to custom-objects. Create folder howto inside.
12. Rename folder request-management to requests. Create folder howto inside.

#### data-access repo in detail

1. data-access/docs/ > superoffice-docs/docs/api/
2. Delete welcome.md
3. Replace toc.yml with 00-custom/toc.yml. Remove ../ prefixes.
4. whats-new/ > superoffice-docs/release-notes/api/. Move the corresponding items from toc.yml to superoffice-docs/release-notes/toc.yml
5. Delete default-index.md and req-*.md from includes/
6. Move folder expander-data-exchange to service.
7. Move person/* to contact/howto/.
8. Move contact/* to company/howto/.
9. Move diary/* to diary/howto/.
10. Move documents/* to document/howto/. Except for plugins to plugin folder. See step 22
11. Move project/* to project/howto/.
12. Move sales/* to sale/howto/.
13. Update tocs to reflect the above moves.
14. Move assets/downloads/* to superoffice-docs/docs/assets/downloads/api/*. assets/downloads.md > assets/downloads/api/index.md
15. custom-fields/overview.md > custom-objects/udef/index.md. Move subfolders of custom-fields to custom-entities/udef/howto/ (See crmscript step for completion) 
16. Rename getting-started > overview (for consistentcy)
17. netserver/index.md > overview/netserver.md
18. Move remaining contents of netserver folder 1 level up.
19. Move contents of netserver/webhooks to automation/webhooks
20. Move netserver/preferences/preferences.md to cache/ TBD
21. Move netserver/preferences/get-set* to admin/user-preferences/howto/
22. Move netserver/erp-connectors and quote-connectors to plugins.
23. Move sentry plugin to plugin folder.

#### crmscript repo in detail

1. crmscript/docs/ > superoffice-docs/docs/automation/crmscript/
2. Replace toc.yml with 00-custom/toc.yml. Remove ../ prefixes.
3. whats-new/ > superoffice-docs/release-notes/crmscript/. Move the corresponding items from toc.yml to superoffice-docs/release-notes/toc.yml
4. Delete includes/*.md
5. Merge contents of superoffice-docs/docs/automation/crmscript-intro.md with crmscript/overview/index.md
6. crmscript/chatbot > superoffice-docs/docs/automation/chatbot/.
7. Move api-reference/CRMScript.Event.yml and api-reference/CRMScript.Event.Trigger.yml to automation/trigger/reference/.
8. persons-and-organizations/ > contact/howto/crmscript/
9. follow-ups/ > diary/howto/crmscript/
10. documents/ > document/howto/crmscript/
11. projects/ > project/howto/crmscript/
12. quotes/ > quote/howto/crmscript/
13. sales/ > sale/howto/crmscript/
14. requests/ > requests/howto/crmscript/.
15. Update tocs to reflect the above moves.
16. Move contents of custom-database:
	extra-fields.md > custom-objects/extra-fields/howto/crmscript/index.md
	extra-tables.md > custom-objects/extra-tables/howto/crmscript/index.md
	udef.md > custom-objects/udef/howto/crmscript/index.md
	sort-extra-field-values.md > custom-objects/extra-fields/howto/crmscript/sort-extra-field-values.md

### CLEAN-UP

* update in and out going links and paths.
* make sure all tocs are accurate
* update mapping in docfx.json
* transfer existing open issues from old repo to superoffice-docs

**Comment by acdavidh** [comment]
This looks like a good idea, I have had the experience multiple times having to look in multiple repo's before finding the content that you are looking for.

**Comment by digitaldiina** [comment]
@SuperOfficeDevNet  suggested additions:

* netserver/erp-connectors and quote-connectors > api/plugins (in Miro but forgot to list it in the steps)

not yet in Miro but is in docfx.json today:

* data-access/docs/documents/plugins > api/plugins/document 
* data-access/docs/security/sentry/plugins > api/plugins/sentry
* data-access/docs/service-soap > service/soap
* superoffice-docs/docs/video-meeting > diary/video-meeting

to match docfx.json URL target:

* rename folder ai-services to ai
* rename folder ui/service-ui to ui/blogic
* rename folder ui/web-application to ui/web-app

**Comment by digitaldiina** [comment]
**Updated instructions** for `git filter-repo --to-subdirectory-filter R1`:

```
git filter-repo --path docs/ --path-rename docs/:docs/TARGET/
git filter-repo --replace-message ../replace.txt
```

where TARGET is the subfolder you graft to. For example, ui or api.

The current version of replace.txt (for ui) is:

<pre>
Merge pull request #==>Merge pull request UI-
#==>UI-issue-
</pre>

**Comment by digitaldiina** [comment]
### Noteworthy URL changes (once the PR is merged and site rebuilt)

- **Webhook reference** is now at automation/webhook/reference/index.html
- **CRMSCript reference** is now at automation/crmscript/reference/index.html
- **Trigger script event reference** is now at automation/trigger/reference/index.htm

- Content about custom fields, udef, custom fields, extra fields, and extra tables is grouped under **custom-objects/index.html**. The new URL for the **UDFHelper class** is custom-objects/udef/howto/entity/udefhelper-class.html
- Old **whats-new pages** are now under release-notes/index.html
- The **API options for contact, company, diary, document, project, quote, sale, and request** now have *howto* instead of *api* in the URL. 
- The content listed in the **Working with...** section of CRMScript is now under the abovementioned API option sections.
