### ISSUE TITLE
Feedback for Consent to app

### ISSUE THREAD

**Issue by Morten-git** [SuperOfficeDocs/superoffice-docs#207]
[Enter feedback here]
Got a question from a developer "What is an administrator?"
In respect to who can approve an application.
Could you elaborate and document (for an non expert SuperOffice user) what an administrator is? I expect it is a specific 'Functional right' - but which one?

If you have been in the "SuperOffice world" for years you would read this as a user with "User level 0" - but I expect it is a specific "Functional right" for the role which allow the user to approve an application (maybe "General administrator"?), but a developer who do not know SuperOffice will not know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [provisioning_consent](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/apps/provisioning/consent.md/#L1)

**Comment by digitaldiina** [comment]
I'll update this together with the new developer portal docs #247.
