### ISSUE TITLE
Feedback for Migration guide

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#208]
We need to include more information about big customers migrating to CRM Online, what can they expect from a "normal" migration and when should they ask for more help from SuperOffice (EMS light weight explanation for partners/customers).
Custom app development in Online on a production sandbox as part of EMS or paid subscription. As all development of new apps, we do not allow them into production *outside the isolated test cluster| without app validation. Keep best practices in mind https://docs.superoffice.com/apps/best-practices.html
Mirroring is not part of EMS, so this is a separate subscription even for EMS sandboxes. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [migration_guide](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/online/migrate/index.md/#L1)

**Comment by digitaldiina** [comment]
Page has been updated after issue was created and now contains sufficient info.
