### ISSUE TITLE
Update tocs for consistency

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#220]
Redesign menus to only open to reveal sub-items when clicked and list index.md files as first menu item titled "Introduction" or "Overview", etc. Be consistent across all tocs!

This issue should catch the remaining inconsistencies **after** completing the "Revise xxx folder" tasks.

**Comment by SuperOfficeDevNet** [comment]
Isn't this just a toc.yml configuration misunderstanding?

**Comment by digitaldiina** [comment]
Replaced by #668
