### ISSUE TITLE
Form in article not migrated

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#23]
Register sub-domain form here not added:  https://community.superoffice.com/en/technical/documentation/identity-management/how-to/federated-sign-in-guide/register-idp/

**Comment by digitaldiina** [comment]
created a "copy" of the register sub-domain form and placed it in a container called forms in the technical club. https://community.superoffice.com/en/technical/forms/register-sub-idp/
