### ISSUE TITLE
Feedback for System user flow

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#241]
This article both mentions "In the future, system user functionality will be replaced with OAuth 2.0 Client Credentials flow, w**hich will not have the sliding expiration behavior.**"

And "The ticket is short-lived and will only last 6 hours."

Please clarify if the ticket has a 6 hours sliding expiration (so 6 hours since last use) or a fixed 6 hours expiration (so 6 hours from generation)

See for discussion: https://community.superoffice.com/en/technical/forums/api-forums/online-web-services/systemuser---validfrom-validto/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [system_user_flow](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/api/authentication/online/auth-application/index.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Added clarifying text in the System User Flow documentation. Checkout this commit(https://github.com/SuperOfficeDocs/superoffice-docs/commit/f0df9e7c12625229eed2678e1c475ef57a5785dc)

**Comment by acdavidh** [comment]
@SuperOfficeDevNet Maybe also add the clarification about the 6 hours to the credential management part of the best practices article?

https://docs.superoffice.com/apps/best-practices.html?tabs=create-rest#credential-management

"Because the ticket is good for 6 hours, "

**Comment by SuperOfficeDevNet** [comment]
> @SuperOfficeDevNet Maybe also add the clarification about the 6 hours to the credential management part of the best practices article?
> 
> https://docs.superoffice.com/apps/best-practices.html?tabs=create-rest#credential-management
> 
> "Because the ticket is good for 6 hours, "

Good to go? [Commit](https://github.com/SuperOfficeDocs/superoffice-docs/commit/84569ed773a1a253c62ac1850d0fccda1b8ba67d)
