### ISSUE TITLE
Feedback for Continuous Database (CD)

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#249]
Not sure where to put this, but when migrating to Online some databases have a databasemodel with problems that will prevent them from migrating _ the OMT stops them.
This article was on old community and I am unable to locate it on new or here
https://community-old.superoffice.com/en/content/content/database/databasemodel---linqpad/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [cdd](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/database/dictionary/index.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
@MargretheR OK?
https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/online/migrate/troubleshooting.md

**Comment by SuperOfficeDevNet** [comment]
[Published](https://docs.superoffice.com/online/migrate/troubleshooting.html) 💯
