### ISSUE TITLE
Add a screenshot with permissions to the Register IdP page

### ISSUE THREAD

**Issue by pavlas77** [SuperOfficeDocs/superoffice-docs#264]
[Register IdP - Microsoft](https://docs.superoffice.com/online/identity/superid/howto/register-idp.html) needs one more screenshot ,as a last step.
Need to get the screenshot in EN.

![image](https://user-images.githubusercontent.com/40568378/163386892-1c8a8065-6d5b-4dda-bc46-747a56f43a50.png)

**Comment by SuperOfficeDevNet** [comment]
Is this not a duplicate issue, https://github.com/SuperOfficeDocs/superoffice-docs/issues/255 ?
