### ISSUE TITLE
Fix nested Plugins menu. 

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/superoffice-docs#297]
![image](https://user-images.githubusercontent.com/15157161/172362934-b9dec13c-f6eb-4773-ad91-0d9fa7f3e89f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [netserver_patterns](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/api/plugins/index.md/#L1)

**Comment by digitaldiina** [comment]
Seems to be fixed already.

![image](https://user-images.githubusercontent.com/23242792/203801842-1973ae91-f7ef-4053-bbc2-9ab020cbd827.png)
