### ISSUE TITLE
Rehome update-app-store-listing form and update incoming links

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#30]
https://community.superoffice.com/en/developer/create-apps/resources/update-app-store-listing/ from SuperOfficeDocs/online-development#8

Where should the form live until the developer portal is up?

**Comment by digitaldiina** [comment]
https://community.superoffice.com/update-application-listing

**Comment by SuperOfficeDevNet** [comment]
Done
