### ISSUE TITLE
Create an actual 404 error page

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#309]
Currently when you open an non-existing link to docs.superoffice.com, you get redirected to the home page, this can be confusing if you open multiple tabs at once. Please create and use an actual 404 page.

**Comment by SuperOfficeDevNet** [comment]
OK, 404 page with link suggestions now deployed.

![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/15157161/321ae82e-6b4c-409d-8239-19019e1a5dd0)
