### ISSUE TITLE
Rehome start-application-validation form and update incoming links

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#31]
https://community.superoffice.com/en/developer/create-apps/resources/start-application-validation/ from SuperOfficeDocs/online-development#8 

Where should the form live until the developer portal is up?

**Comment by digitaldiina** [comment]
https://community.superoffice.com/validate-custom-application

**Comment by SuperOfficeDevNet** [comment]
Done
