### ISSUE TITLE
Docs links from CRMScript intellisense are broken

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#310]
When opening a Docs links from the CRMScript intellisense, they are all redirect to the homepage (so 404).

Example:
![image](https://user-images.githubusercontent.com/40491305/172637010-750a78c6-ed76-48f7-bc4a-48ede4fab09c.png)

Tested on sod.superoffice.com, SuperOffice CRM Online 10.1 Build Release_10.1.4_2022.06.08-01

**Comment by SuperOfficeDevNet** [comment]
Register as bug ID 29551.

**Comment by SuperOfficeDevNet** [comment]
This [bug is solved](https://community.superoffice.com/en/product-releases/bugs-wishes/product-issue/?bid=29551&azure=1), and SOD now has the correct links again, will be in production soon.
