### ISSUE TITLE
Rehome start-application-certification form and update incoming links

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#32]
https://community.superoffice.com/en/developer/create-apps/resources/start-application-certification/ from SuperOfficeDocs/online-development#8 '

Where should the form live until the developer portal is up?

**Comment by digitaldiina** [comment]
https://community.superoffice.com/certify-application

**Comment by SuperOfficeDevNet** [comment]
Done
