### ISSUE TITLE
Feedback for Getting started

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#322]
Could you add this form like the other app registrations on docs
https://online2.superoffice.com/Cust1990/CS/scripts/customer.fcgi?action=formFrame&formId=F-vnSyUAxe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [mirroring_getting_started](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/mirroring/getting-started/index.md/#L1)

**Comment by digitaldiina** [comment]
Already included.
