### ISSUE TITLE
Rehome new-app-store-listing form and update incoming links

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#33]
https://community.superoffice.com/en/developer/create-apps/resources/new-app-store-listing/ from SuperOfficeDocs/online-development#8 

Where should the form live until the developer portal is up?

**Comment by digitaldiina** [comment]
https://community.superoffice.com/new-application-listing

**Comment by SuperOfficeDevNet** [comment]
Done
