### ISSUE TITLE
Feedback for Migration guide

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#331]
A few notes:
* Please include info about that you need to remove references to 'SentryAddonNames' in the userpreference table before you can continue past the start screen
* The caution info lists the following "When the OMT is started, users are prevented from logging into SuperOffice Service and SuperOffice Windows App.", this can be read like as soon as you start the OMT program that frozen is added, but it actually only is done when starting the upload/migration.
* Include info to register the identify provider for the customer domain name (https://docs.superoffice.com/online/identity/superid/howto/register-idp.html) **before** doing any migration, so that users can immediately login using IDP and you don't need to do any migration/user-transition later
* Note that a log file is written to %temp%\SoMigration
* Note which resources the OMT needs access to (database, so arc folder, customer service installation folders)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [migration_guide](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/online/migrate/index.md/#L1)

**Comment by digitaldiina** [comment]
Thanks for this detailed feedback, @acdavidh. We'll follow up.
