### ISSUE TITLE
Rehome developer-registration form and update incoming links

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#34]
https://community.superoffice.com/en/developer/create-apps/resources/developer-registration/ from SuperOfficeDocs/online-development#8 

Where should the form live until the developer portal is up?

**Comment by digitaldiina** [comment]
https://community.superoffice.com/register-as-developer

**Comment by SuperOfficeDevNet** [comment]
Done
