### ISSUE TITLE
Feedback for Logging in NetServer

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#363]
XML declaration are missing the ending /

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [logging_netserver](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/api/logging/index.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Appreciate the PR! 👍
