### ISSUE TITLE
Rehome activate-custom-application form and update incoming links

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#37]
https://community.superoffice.com/en/developer/create-apps/resources/activate-custom-application/ from SuperOfficeDocs/online-development#8

Where should the form live until the developer portal is up?

**Comment by digitaldiina** [comment]
https://community.superoffice.com/activate-custom-application

**Comment by SuperOfficeDevNet** [comment]
Done
