### ISSUE TITLE
Mobile CRM help - info

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#370]
There is an old Pocket CRM help from version 8.
A little outdated, but it's a start.

https://help.superoffice.com/Documentation/Help/EN/PocketCRM/8.0/WebHelp/index.htm#t=topics%2Fcopyright.htm

I will upload the html files into the folder on the norfilepub server:
\\norfilepub\rnd\Semantix Ink\Help

**Comment by digitaldiina** [comment]
- [ ] #737
