### ISSUE TITLE
Update links to SDK docs

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#38]
- [x] https://community.superoffice.com/en/sdk-docs/
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-SOAP-SOAP.htm
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-WebAPI-WebAPI.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.WinGui/webframe.html
- [x] http://devnet.superoffice.com/documentation/SDK/SO.WinData/webframe.html
- [x] https://community.superoffice.com/Documentation/SDK/SO.WebGUI/Index.html
- [x] https://community.superoffice.com/documentation/sdk/SO.CustomerServiceSupport/Index.html
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-SOAP-SOAP.htm
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-WebAPI-WebAPI.htm
- [x] http://devnet.superoffice.com/documentation/SDK/SO.Server.Data/Index.html
- [x] http://devnet.superoffice.com/documentation/SDK/SO.Server.Services/Index.html
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-WebAPI-WebAPI.htm
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-SOAP-SOAP.htm
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-SOAP-Services86-Contact-GetContactEntity.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.NetServer.Data.Access/html/0ca0cab8-0ca1-4aad-82f0-d244eb54b4f5.htm
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/v1SaleEntity_GetAll.htm
https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/v1FindAgent_FindFromRestrictionsColumns.htm
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-Reference.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.Database/html/Tables-appointment.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.Database/html/Tables-associate.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.Database/html/Tables-contact.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.Database/html/Tables-person.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.Database/html/Tables-project.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.Database/html/Tables-projectmember.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.Database/html/Tables-sale.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.Database/html/Tables-SaleStakeholder.htm
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-WebAPI-Agents-BulkUpdate\_Agent-BulkUpdate\_Agent.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.NetServer.Data.Access/html/Introduction-Commonpatterns-PluginPattern.htm
- [x] https://community.superoffice.com/documentation/SDK/SO.NetServer.Data.Access/html/DevelopersGuide-ERPConnectors-ERPSyncConnectorInterface-ERPSyncConnectorInterface.htm
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-WebAPI-REST-REST.htm
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-WebAPI-Agents-Agents.htm
https://community.superoffice.com/documentation/SDK/SO.NetServer.Data.Access/html/netserver_configuration_webapi.htm
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-WebAPI-REST-Search.htm
- [x] https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Reference-WebAPI-Authentication-Authentication.htm
- [x] https://community.superoffice.com/webapi/rest

**Comment by digitaldiina** [comment]
@AnthonyYates can you close issue if this is ok?

**Comment by SuperOfficeDevNet** [comment]
Done
