### ISSUE TITLE
Help: Admin - Template variables - Missing Quote ID (quid)

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#382]
https://help.superoffice.com/Documentation/Help/EN/CRM/WebHelpAdmin/index.htm#t=Template_variables.htm

In the header for: **Variables for Quote info**
We need to add the variable for Quote ID = quid

- [x] Add to docs ( @pavlas77 )
- [x] Add to community Admin guide ( @kirstiaa )
- [x] Add to Help Admin ( @thaugholt )

**Comment by pavlas77** [comment]
@kirstiaa Quote ID added to the Template variables reference page https://docs.superoffice.com/document/templates/variables/for-quote-info.html. Should I keep this Issue open so it is also added to the Help - Admin - Template variables reference?

**Comment by kirstiaa** [comment]
Yes, @pavlas77 Martin, please keep it open since there are multiple assignees here :)
I'll add a little more data in the description

**Comment by thaugholt** [comment]
Updated in RoboHelp (User/Admin) and GitHub
