### ISSUE TITLE
Feedback for DbSetup.exe

### ISSUE THREAD

**Issue by samuelholmstroem** [SuperOfficeDocs/superoffice-docs#384]
Hi!

We are stating this:
_"DbSetup will export & import all standard tables & fields for both products.
DbSetup does not see extra tables and extra fields. We will have a separate solution for that."_

But there are no info about what the solution/tool is. 
Would be good to state how a customer should do a full backup including Service/custom tables. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [dbsetup_exe](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/onsite/install/database/dbsetup-exe.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Hi Samuel!

The docs are wrong. This information was true prior to SuperOffice version 8.0. When SuperOffice introduced CDD, it DBSetup also inherited the ability to export extra tables/fields, and related data. 

That said, DBSetup is NOT a backup tool. Onsite companies MUST have their own database backup strategies that do not involve DBSetup - it is NOT a backup tool. 

We will fix the docs to reflect that an export and import includes all tables and fields.
