### ISSUE TITLE
Soft-delete: affected table list

### ISSUE THREAD

**Issue by AnthonyYates** [SuperOfficeDocs/superoffice-docs#40]
Create a list of affected tables when a soft-delete occurs.

Consider adding/linking to [Soft-delete article](https://github.com/SuperOfficeDocs/superoffice-docs/blob/08a59c5476217a9bee827977070e31a8ef897c9c/docs/soft-delete.md).

From the [community forums](https://community.superoffice.com/en/developer/forum/rooms/topic/gen-dev-group/general-dev-api/what-does-hard-delete-person-and-company-delete/).

**Comment by ejfasting** [comment]
Add link/documentation to/for:
* RecycleContact
* RecyclePerson
* RecycleTicket
These can be used to get entities which are soft-deleted. 
![Untitled](https://github.com/user-attachments/assets/a8db45e7-326d-4c85-bacb-d8ff486fd38b)



Updated link to [Soft-Delete](https://docs.superoffice.com/en/security/privacy/soft-delete.html)

**Comment by ejfasting** [comment]
The affected tables/fields can be found in fileset.

Contact: /Modelling/Source/SuperOffice.CD.DSL.Implementation/Consistency/DeepDeleteContactActionMap.cs
Person: /Modelling/Source/SuperOffice.CD.DSL.Implementation/Consistency/DeepDeletePersonActionMap.cs
