### ISSUE TITLE
Sales target - License on Target type (extra group or dimension)

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#418]
Info added to:
- [x] Community User guide ( @kirstiaa  + @Chrihagb )
  - [x] Create new page structure
  - [x] Write new text with expanded functionality
  - [x] Publish by 19.sept
- [x] Help User ( @thaugholt )

https://help.superoffice.com/Documentation/Help/EN/CRM/UserHelp/index.htm#t=StandardCRM%2fsale%2fSales_targets.htm

**Feature 1: License on 2nd dimension**
Ester Kate Jansson 29.08.2022 13:00 • 
Jeg tenker at noe som bør nevnes er at man kun får lov til å legge inn et company target + et group target om man ikke har lisensen unlimited sales targets. Har man ikke den lisensen så får man ikke lagt til flere. Da blir man promptet til å kjøpe den. Så i paragrafen om Add target to a new year, punkt 11, bør det kanskje spesifiseres? om det ikke nevnes i starten at det neste som kommer gjelder kun om du har lisens. 
Ellers står det det ikke noe feil.

**Feature 2: Export to excel + export from one line to another line**

Spec: https://superofficenorge.sharepoint.com/:w:/r/sites/design/Delte%20dokumenter/Dashboards%20%26%20Sales%20targets/Sale%20targets/Spec%20-%20Sales%20targets.docx?d=w8ddb0b1bd11d43399818a4ee556f171f&csf=1&web=1&e=f5WlQh

https://superofficenorge.sharepoint.com/:w:/r/sites/design/Delte%20dokumenter/Dashboards%20%26%20Sales%20targets/Spec%20-%20Advanced%20Sales%20Targets.docx?d=w3b8231148a5848c68f1797d4731714ff&csf=1&web=1&e=pcVgdg

**Comment by thaugholt** [comment]
**Sales Premium** - i spec står det om mulighet til å slette **All sales** og legge inn en annen dimensjon, men i GUI er det ikke mulig å slette **All sales**. Så jeg antar at **Sales Premium** bare har **All sales**?
Torgeir

**Comment by kirstiaa** [comment]
@thaugholt You do mean target typen: All sales - Amount? I have asked Tone about this, will update the answer.
-Kirsti

**Comment by thaugholt** [comment]
OK ,takk! :-)

**Comment by thaugholt** [comment]
I have updated this in RoboHelp and will send a build for check at your end. Will update md files in Github afterwards.

**Comment by kirstiaa** [comment]
@thaugholt - About the export functionality:
**Export**
Click the Task button to export the sales target for the selected year to Excel.

It's also possible to copy from excel and paste it inside sales target.
Copy the rows you want - set marker on top left cell and paste.
Note: If some rows are **Locked**, it's not possible to paste into it.
Just make sure that you copy from excel on the same rows that you want to paste it.

**Comment by thaugholt** [comment]
Thanks! Have added this info also.
