### ISSUE TITLE
Feedback for System user flow

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#439]
New screenshot - this time from the develper portal and system user template :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [system_user_flow](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/api/authentication/online/auth-application/index.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Completed in [this commit](https://github.com/SuperOfficeDocs/superoffice-docs/commit/b0277ffc810dbf0fa1cdd25295585fdd6e197bb6).
