### ISSUE TITLE
Update IDP docs note about custom IDP support.

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/superoffice-docs#447]
https://docs.superoffice.com/online/identity/federated-id-and-identity-providers.html

State: 

Use Microsoft or Google as federation gateway with your custom IDP.

**Comment by pavlas77** [comment]
@SuperOfficeDevNet Where should the sentence "Use Microsoft or Google as federation gateway with your custom IDP." go please?
