### ISSUE TITLE
Turn off image scale on hover for mobile

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#450]
On mobile (touch-screen) devices, the image scale is always active. This restricts the content width on all pages that have screenshots.

For example, open the [Video meeting page](https://docs.superoffice.com/diary/video-meeting/index.html) on your mobile.

Affected CSS block:

```
.article img[alt$="-screenshot"]:hover,.tab-content img[alt$="-screenshot"]:hover
```

Suggest adding a restriction to the scaling logic. Something like:

```
@media only screen  and (min-width : 1224px)
```

Source: [Stackoverflow](https://stackoverflow.com/questions/6370690/media-queries-how-to-target-desktop-tablet-and-mobile)

**Comment by SuperOfficeDevNet** [comment]
The suggested fix was not necessary.
