### ISSUE TITLE
Help & Guide: Admin - Configurable screens - Sale & Project

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#459]

**Comment by thaugholt** [comment]
@kirstiaa 
In Edit layout for archives/Section tabs: You can define advance options for single/double click to change default behaviour.
1. Do you have any examples / use cases for these options? What would be a good example to illustrate the usefulness of changing these options?
2. Do you have a link to additional resources for setting up url and soprotocol?
Torgeir
