### ISSUE TITLE
Migrate document migration content from Epi

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#49]
Content is in a hidden folder on Epi with works in progress. Need to be migrated to a branch before we pull the plug on Epi.

![415a384f-dbd7-43d4-ad6f-3008629ff321](https://user-images.githubusercontent.com/23242792/111998984-d42d0f00-8b1c-11eb-92fa-0dba7d915a2a.PNG)

**Comment by SuperOfficeDevNet** [comment]
@pavlas77 , any update here? WIll you migrate these docs, otherwise close the issue.

**Comment by digitaldiina** [comment]
@pavlas77 I'm closing this issue. If it becomes relevant in the future, please reopen this issue rather than creating a new one.
