### ISSUE TITLE
Help: User - Form - Create a new form - Wrong url for link to Google analytics in the Properties section

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#502]
- [x] Update RoboHelp - Torgeir
- [x] Update GitHub - Kirsti

https://help.superoffice.com/Documentation/Help/EN/CRM/UserHelp/index.htm#t=Mailing%2FHelptopics%2Fform_create.htm

Requests: https://online2.superoffice.com/Cust1990/CS/scripts/ticket.fcgi?_sf=0&action=doScreenDefinition&idString=cs_viewTicket_is&entryId=3292675

**Help links are wrong**
We have documentation thar refers to community parts that not exists.

Use Google Analytics: Select this option to track the form and connect it to Google Analytics (if that is set up for your web site). In the field below this option, you can enter the Google Analytics tracking ID for this form. Read more on SuperOffice Community: Simple Google Analytics e-mail tracking.

![Image](https://user-images.githubusercontent.com/102585577/194874919-1fec9122-71a5-4acc-b738-b3cb91de71c0.png)

https://community.superoffice.com/en/technical/blogs/simple-google-analytics-email-tracking/

Correct link seem to be:
https://community.superoffice.com/en/technical/blogs/archive/simple-google-analytics-email-tracking/
 

Hälsningar / Best regards,

Gustaf Cullin
Senior Customer Relationship Management Consultant | SuperOffice Sweden AB

**Comment by thaugholt** [comment]
URL fixed in RoboHelp. Must be fixed in md file also.
