### ISSUE TITLE
Help admin: Wrong info on Fields about 1.page fields

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#504]
URL:  https://help.superoffice.com/Documentation/Help/NO/CRM/10.1/WebHelpAdmin/index.htm#t=fields_web%2FFields_web.htm

 

![Image](https://user-images.githubusercontent.com/102585577/199931687-9f9861bf-57d7-42ac-b4d4-04d7a9f8f963.png)

**Comment by thaugholt** [comment]
Update in RoboHelp and Github
New text in note: Please note that this may not be applicable if you are using another layout via Screen designer.
