### ISSUE TITLE
Add Web Tools for Mac documentation

### ISSUE THREAD

**Issue by pavlas77** [SuperOfficeDocs/superoffice-docs#508]
- How to install - can we link to https://community.superoffice.com/en/learning/user-guide/get-started/connect-email-documents/mac-document-integration/
- Enterprise installation - Max and Mindaugas will provide info
- Troubleshooting - move the section about Mac Web Tools here from Web Tools for Win

- System Requirements - point to Online System requirements

**Comment by digitaldiina** [comment]
@pavlas77 There is a page on docs now covering WebTools for Mac. Is this sufficient to close this issue, or do you need more?

superoffice-docs\docs\en\webtools\learn\install-mac.md

**Comment by pavlas77** [comment]
@digitaldiina Yes, looks good, we can close this one.
