### ISSUE TITLE
Documentation wrong for :NSUserDefinedFieldInfoAgent.GetPublishedUserDefinedFieldFromProgId

### ISSUE THREAD

**Issue by pavlas77** [SuperOfficeDocs/superoffice-docs#510]
From Morten Larsen, SOS ID 3296465

Just tried to use NSUserDefinedFieldInfoAgent.GetPublishedUserDefinedFieldFromProgId to get info about a userdefined field for project.

According to documentation parameter 2 (ownerType) is an integer of type UDefType. According to Enum documentation of UDefType, 9 would be the project table, but that throwed an error. Then I used trial an error and found that ownerType=3 returned the info about the project field. (btw 1: contact, 2: person .. I did not test the rest)

Ie it seems like the documentation is not correct – either ownerType should not be of type UDefType or UDefType have the wrong values.

Maybe a new function or agent for custom fields should be introduced to handle both extrafields and userdefined fields.

Documentation look like this:
https://docs.superoffice.com/automation/crmscript/reference/CRMScript.NetServer.UDefType.html
![image](https://user-images.githubusercontent.com/40568378/201038751-2ff50e3e-f592-4d3a-8e76-d77352241edf.png)

https://docs.superoffice.com/automation/crmscript/reference/CRMScript.NetServer.NSUserDefinedFieldInfoAgent.html#CRMScript_NetServer_NSUserDefinedFieldInfoAgent_GetUserDefinedFieldFromProgId_String_Integer_
![image](https://user-images.githubusercontent.com/40568378/201038828-ad289ef3-8ea2-4e64-afd4-2a124794c383.png)

**Comment by SuperOfficeDevNet** [comment]
This is a big in CRMScript, not the documentation.

BUG 35751
