### ISSUE TITLE
Guide with docs help - How to display the iframe of help in docs inside guides as long as it's stored in Community?

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#514]
How can we solve the iframe issue?
With the help files, there has been created an xml folder, that only shows the help page, not the menu or anything else.
https://help.superoffice.com/Documentation/Help/EN/CRM/UserHelp_XML/StandardCRM/Dashboard/Dashboard_View_and_filter.htm

As long as User and Admin guide is located in Community, we need a good solution to show only the help page on Community.
This is only until the guides are stored in GitHub/docs, then we can use Include section.

![Image](https://user-images.githubusercontent.com/102585577/201873311-2a651c92-0a89-4997-902c-f35ba33d8ba8.png)

**Comment by kirstiaa** [comment]
Yes, @SuperOfficeDevNet, that is true, but for now we do not have all guides inside docs, so need to have a temporary solution before guides are moved. :-)

**Comment by kirstiaa** [comment]
@SuperOfficeDevNet Yes, that iframe contains the help on docs, but all the community pages are still located in community, those are not yet in docs. So when we show the help pages in community we have used the xml files of help to show specific pages where ever we need to, on the User and Admin guide in Community.

For some time we do need to have a solution for how we want to show the current help (that is in docs, with the menu etc.).

**Comment by SuperOfficeDevNet** [comment]
Ah, to bring docs content into community then? That too would bring in the whole site (navbar and menus). I think the best solution is to port the content over, which is a small project that would take ~2-3 weeks to complete. To have the same content on community would require community create a new Block type that can import markdown content from github (or index a cloned repo) instead, similar but different to what's done with the XML files today. 

This needs more discussion. :-)

**Comment by digitaldiina** [comment]
Migration done in #562
