### ISSUE TITLE
Warning vs info on app specific page

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#521]
Page use red for mandatory fields that are not filled
![image](https://user-images.githubusercontent.com/22498774/202433375-666398fd-1388-4199-bf0d-1e883e6f027d.png)

And orange for fields that are mandatory before publish, but you may save without correcting
![image](https://user-images.githubusercontent.com/22498774/202433527-5e27c0ab-1777-45b9-8e08-e7e8dbe7a6ec.png)

the word required should probably be replaced with something that better indicates what it is when it's the orange infos

**Comment by digitaldiina** [comment]
@MargretheR can we update the text in the **Save** dialog?

- `->` should be just `>`
- `&` should be `and`
- Casing and singular/plural should be the same as in the UI

**Comment by MargretheR** [comment]
> can we update the text in the **Save** dialog?
> 
> * `->` should be just `>`
> * `&` should be `and`
> * Casing and singular/plural should be the same as in the UI

Added to backlog (dev portal)
