### ISSUE TITLE
Help: User - Sales target - Target type for Category is Company category, not sales category

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#525]
https://help-sod.superoffice.com/Documentation/Help/EN/CRM/UserHelp/index.htm#t=StandardCRM%2Fsale%2FSales_targets.htm

Add target type
....
In the next list, you can select specific elements of the target type you have selected. If you do not select any, all will be included. Example: If you selected Category as target type, you can select the **sales categories** for which you want to create targets.
...

...sales categories are not correct, it should be
company categories

![Image](https://user-images.githubusercontent.com/102585577/202673083-d8207727-9afb-47dc-bf17-c95830e66a44.png)

The drop down for sales targets are grouped on 
- Sale
- Company

![Image](https://user-images.githubusercontent.com/102585577/202673679-d1041189-f314-4a8c-bdac-d4c84b1884f9.png)

**Comment by thaugholt** [comment]
Fixed in Robohelp and Github
