### ISSUE TITLE
Show audience + envir metadata in time-to-read line

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#533]
Add icon or text revealing:

- admin vs. regular user
- online vs. onsite

Find info in yml frontmatter metadata.
Place at the top of the page where we display time to read.

**Comment by kirstiaa** [comment]
We would love to have an icon showing that this page is a admin page/setting page where you need to log into Settings and maintenance

Possible icon to show:
🔧 : wrench : 

![image](https://user-images.githubusercontent.com/102585577/204744504-8f1ae5e4-4cd3-4b69-97e1-fe4d9240f53b.png)

**Comment by digitaldiina** [comment]
@digitaldiina change so.user to so.audience. Try to do the same for so.envir
