### ISSUE TITLE
Docs Search: Search result also shows all the includes md-files - and it looks odd when clicking

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#574]
Some of the search result comes up with no titel only " | SuperOffice Docs"
Clicking that link will open a page with no content other that the include md file.

Expected that the include files should not be indexed and shown in the search result.

![Image](https://user-images.githubusercontent.com/102585577/209931349-39aa35e8-680c-439f-b97e-6ea3506423e8.png)

**Comment by SuperOfficeDevNet** [comment]
All *includes* folders must be excluded in the configuration file.

**Comment by digitaldiina** [comment]
@SuperOfficeDevNet, I implemented the requested changes on superoffice-docs main branch.

However, docfx-learn.json in build-docs must also be updated and I lack access.


Add general exclude at the top (becomes lines 9-11): 
```
    "content": [
      {
        "src":"docs",
        "files": [ "*.{md,yml}" ]
      },
      {
        "exclude": ["**/includes/**"]
      },
```      

Add exclude (1 line) to existing release-notes entry, ca line 100:

```
{
        "src":"superoffice-docs/release-notes",
        "dest":"en/release-notes",
        "files": [ "**/**.{md,yml}", "*.{md,yml}" ],
        "exclude": ["**/includes/**"]
}
```
