### ISSUE TITLE
Fix broken [include]

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/superoffice-docs#576]
Fix the syntax issue so that the included content is added to the rendered page...
Either the include directive is not supported inside HTML elements, or there is a missing extra line breaks before and after the details elements and the include directive.

![image](https://user-images.githubusercontent.com/15157161/210084769-a3d2bbc8-8391-44a0-8434-c650ba1121f1.png)

This should have been detected in the PR or in [staging](https://superofficedocs.github.io/superoffice-docs/en/admin/user-management/learn/role/index.html)

**Comment by digitaldiina** [comment]
Pushed fix/enhancement on main. The culprit is the lack of blank lines. Affects not only includes but all Markdown formatting, such as bold. Have to look into creating a filter that can catch this in CI tests when I'm back.

**Comment by digitaldiina** [comment]
Solved by commits [1984c6a](https://github.com/SuperOfficeDocs/superoffice-docs/commit/1984c6a55e87d52be1073cfdcb8a76c4f5e2e46f) and [34bb32b](https://github.com/SuperOfficeDocs/superoffice-docs/commit/34bb32b85ffc3c01d25c514be72601d892154b79) in branch *combine-hc-and-requests*.
