### ISSUE TITLE
Learn: 10.2.1 Changes to Help - New list: Task menu

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#592]
Hei Hanne!
Vi fikk vite at det kom en ny type liste i Settings and maintenance nå i 10.2.1 versjonen som treffer brukerne våre i neste uke.
Det er en liste som egentlig har bodd sammen med GUI – Web panel, men den blir nå trukket ut og lagt opp som en egen liste.

![Image](https://user-images.githubusercontent.com/102585577/212024961-f957f072-e871-4109-a139-55b149e0e058.png)
 
Da bør litt av Web panel listen endres på, slik at det ikke står noe som er overlappende, og kanskje ha en Reference link til den nye filen.
[https://docs.superoffice.com/en/admin/lists/learn/web-panel-add-item.html](https://url4.mailanyone.net/scanner?m=1pFbsB-0001X4-4F&d=4%7Cmail%2F14%2F1673446200%2F1pFbsB-0001X4-4F%7Cin4d%7C57e1b682%7C13051142%7C7344037%7C63BEC44B0BA38954BFDDF2275B00B10A&o=%2Fphto%3A%2Fdtsrscsfpeo.umefieco%2Fc.%2Fdn%2Fiinlamr%2Fst%2Feansle-we-anlbpm-adhte.dilmt&s=T2ncAIqHtUXsrxuZOv9ijSvG1z8)
 
På GitHub i bransjen for 580, så har vi laget en ny fil for den nye listen, men dette er kun en kopiert fil, så all tekst der må skrives på nytt.
[https://github.com/SuperOfficeDocs/superoffice-docs/blob/580-TOC-changes/docs/en/admin/lists/learn/add-items-to-task-menu.md](https://url4.mailanyone.net/scanner?m=1pFbsB-0001X4-4F&d=4%7Cmail%2F14%2F1673446200%2F1pFbsB-0001X4-4F%7Cin4d%7C57e1b682%7C13051142%7C7344037%7C63BEC44B0BA38954BFDDF2275B00B10A&o=%2Fphti%3A%2FgtsmbthSco%2Fu.irupeffceOpsDorsuec%2Fdiofce-ofc5ls%2F0b%2F8boaC-TgchnO-%2Fdesncse%2Folm%2Fasn%2Fidinltsaar%2F%2Fesiddtem--tmao-nk-etsdm.u&s=fFc28Zc8BzqMUIGeMbzA_7dIEG0)
 
Se vedlagt fil på kapittel 1c: Task menu items for mer info.
 
Tror du at du klarer å få skrevet det til begynnelsen av neste uke?
For å gjøre det enkelt, så tenker jeg det er greit at du sender teksten til oss, så legger vi det inn?
 
PS! Jeg tror egentlig ikke det er skrevet noe om første delen av spec’en som jeg sender med. 
Custom dialogs
[https://docs.superoffice.com/en/release-notes/10.1/admin/10.1.9-update.html](https://url4.mailanyone.net/scanner?m=1pFbsB-0001X4-4F&d=4%7Cmail%2F14%2F1673446200%2F1pFbsB-0001X4-4F%7Cin4d%7C57e1b682%7C13051142%7C7344037%7C63BEC44B0BA38954BFDDF2275B00B10A&o=%2Fphto%3A%2Fdtsrscsfpeo.umefieco%2Fc.sen%2F-eaerl0eno1%2F1.ts1m%2Fa.n%2F0dia-1.epdt9ulmth.&s=bpj_82QY_lIJKrP5DxY8aBYljr8)
 
Så mulig det også bør skrives om for Settings and maintenance – under CRMScripts. Se litt på det 😊
 
Har du hørt noe fra Tony? Vet han skal være med på en Boot camp med SuperOffice i Tyskland, så kan hende han er opptatt.
Vi snakkes!

**Comment by SuperOfficeDevNet** [comment]
Duplicate to #588
