### ISSUE TITLE
Update screenshots for v 8/9

### ISSUE THREAD

**Issue by pavlas77** [SuperOfficeDocs/superoffice-docs#60]
- [x]  http://localhost:8080/docs/onsite-setup/web-client/set-up-web-and-report.html - screenshot are from v6
- [x] http://localhost:8080/docs/onsite-setup/crm-server/iis-web-server/prepare.html - update screenshots of IIS on Windows Server 2012+

**Comment by SuperOfficeDevNet** [comment]
@pavlas77 Any progress update here? 

> [!NOTE] 
> Please use live links, i.e. do not link to localhost:8080
