### ISSUE TITLE
Learn: Wrong numbering when adding include text

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#613]
https://docs.superoffice.com/en/email/service/learn/create-mailbox.html

When an include text are added, the numbering and order of numbers are messed up.

![Image](https://user-images.githubusercontent.com/102585577/216937204-da0efde1-51d1-48a3-9d4c-2c2c237af960.png)

**Comment by digitaldiina** [comment]
When you place list numbering inside an include file, both the fragment and the target list should use '1.' for all steps instead of explicit numbers to make the fragment reusable.

**Comment by kirstiaa** [comment]
![image](https://user-images.githubusercontent.com/102585577/221808172-318051eb-91bb-4a43-ad35-9482561bc244.png)

All of the numbers are added as 1. - both in the md file and all the include files.
But it still shows with wrong numbering when an include file witch include a numbering ( all added as 1.).

**Comment by SuperOfficeDevNet** [comment]
This does appear to be a valid issue.

**Comment by kirstiaa** [comment]
I'm no expert, but for me it looks correct in the md file. I think Bergfrid need to check if it's something wrong here? If using Include files with numbering is a bad idea, etc.?

**Comment by digitaldiina** [comment]
Refactoring done on branch *combine-hc-and-requests*.
