### ISSUE TITLE
Developer menu items reconciliation

### ISSUE THREAD

**Issue by xt1** [SuperOfficeDocs/superoffice-docs#635]
Suggestion to reconcile some of the items in the DEVELOPER 

![image](https://user-images.githubusercontent.com/3820037/223354991-cefca221-4bab-46a1-910b-e1629620d84a.png)

There are three Database entries:
* Database overview
* Database mirroring
* Database tables reference

The overview should link to the other two, so that the mirroring and table reference can be removed from the menu.

The **Introduction to APIs**  should likewise link to the CRM Script, Automation, WebAPI, SOAP, and Services references.

Add a **WebAPI overview** menu item to lead people to the WebAPI documentation and reference.

**Comment by xt1** [comment]
Drop the "Database table reference" link from the menu. - it's available from the "Database overview"

Add a link to "WebAPI Overview"  `docs\en\api\reference\restful\index.md`  to the menu

**Comment by digitaldiina** [comment]
Implemented
