### ISSUE TITLE
Add CRMScript.DataStructure.yml to reference Library

### ISSUE THREAD

**Issue by ejfasting** [SuperOfficeDocs/superoffice-docs#651]
**Describe the solution you'd like**
Adding CRMScript.DataStructure.yml to the Reference-library. 

Second request would be to move Vector and Map from Native to Datastructure, to not have them defined twice in the documentation. 

**Additional context**
Snippet from toc.yml: 

![image](https://user-images.githubusercontent.com/60758190/228794971-1970d312-5124-4f82-ba26-f433d69dad19.png)

**Comment by SuperOfficeDevNet** [comment]
That's an interesting suggestion! Will give this serious consideration.

**Comment by juleiste** [comment]
Not to include more 'stuff' into this, but I've also noticed you have added some .md-files for 'Data Types' under CRMscript:
![image](https://user-images.githubusercontent.com/60758190/228809629-709dfffb-eab8-4ba0-a05a-6d31a8081c1c.png)

This includes Generic and EventData, and the description in these looks to be more extensive then the ones under references. 

Generic is added as a class (CRMScript.Native.Generic), but it doesn't contain any valuable information/description
