### ISSUE TITLE
Learn - Translation - Import of translated learn content

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#688]
## From SuperOffice
Zip sent to Semantix - created from branch: combine-hc-and-requests
Changes 
from 31.03.2013
to 20.04.2023

[docs-en-learn.changes-final.txt](https://github.com/SuperOfficeDocs/superoffice-docs/files/11475736/docs-en-learn.changes-final.txt)
[docs-en-learn-final.zip](https://github.com/SuperOfficeDocs/superoffice-docs/files/11475737/docs-en-learn-final.zip)

Yml files, that was not included in the final zip send to Semantix in april. Sent 06.06.2023
[en-learn-yml.zip](https://github.com/SuperOfficeDocs/superoffice-docs/files/11676208/en-learn-yml.zip)

---
## From Semantix

Translated NO files in zip-file 02.06.2023:
[Semantix-20230602-docs.zip](https://github.com/SuperOfficeDocs/superoffice-docs/files/11634506/Semantix-20230602-docs.zip)

New updated Zip-file from Semantix 07.06.2023:
[Semantix-20230607-docs.zip](https://github.com/SuperOfficeDocs/superoffice-docs/files/11676250/Semantix-20230607-docs.zip)

**Comment by digitaldiina** [comment]
Updated docfx-learn-light.json

![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/23242792/478f4741-4fca-4207-963f-b0f9dae1abc1)
