### ISSUE TITLE
Trouble shooting consent - not admin in OC

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#69]
Consent not possible 
Error - your account does not have....
![image](https://user-images.githubusercontent.com/22498774/119777809-fc434080-bec6-11eb-9667-6acca4815f59.png)

OC does not know user as admin. Log in to admin - make a change to the user - save - change back - save
Now, you may approve

Add here http://docs.superoffice.com/apps/provisioning/get-consent.html

**Comment by SuperOfficeDevNet** [comment]
Added troubleshooting info
