### ISSUE TITLE
Learn: Admin - Add template variables for Quote inside the whole overview

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#707]
https://help.superoffice.com/Documentation/Help/EN/CRM/WebHelpAdmin/index.htm#t=Template_variables.htm%23Quote_line_subscription_variables

Need a link to the pdf that shows all the quote template variables and how to set up the doc template.

The pdf is stored inside the help, but it's not linked on the variables page, and that is missing.

https://help.superoffice.com/Documentation/Help/EN/CRM/WebHelpAdmin/Quote_templates.pdf

SuperOffice CRM
# Quote templates
CONTENTS
Quote templates ..............................................................................................................3
Design......................................................................................................................................................4
Preparations.............................................................................................................................................5
Create a sale for testing the template document.................................................................................5
Select the fields to be displayed..........................................................................................................5
Copy the template to be modified........................................................................................................5
Link the template document to a sale type..........................................................................................6
Modify the template..................................................................................................................................6
Insert fields in Word.............................................................................................................................6
Insert fields in the template document.................................................................................................7
View the order confirmation in SuperOffice CRM................................................................................8
Grouping and sorting of products ........................................................................................................8
Customisation options............................................................................................................................10
Formatting .........................................................................................................................................10
Numbers............................................................................................................................................11
Date/time...........................................................................................................................................11
Settings for language and country ("culture")....................................................................................11

## Quote templates
Note: This document is an excerpt from SuperOffice CRM Administrator
Training.
The templates for quote documents, quote details and order confirmations differ
from ordinary document templates, as they use "mergefields" in addition to
standard template variables.
• The quote document is the document that is available via the link on
the Quote section tab and via the Print button.
• The quote details are generated as a PDF file together with the quote
document (if one is created) when you click Send on the quote.
• The order confirmation is generated as a PDF file together with the
quote document (if one is created) when you click the Place order
button.
A quote often consists of more than one product. It is therefore necessary to
create a quote details template (and an order confirmation template) in which
each product is listed in a table with different groupings (e.g. alternatives).
The user will only be able to edit the quote document in Word. The quote
details template and the order confirmation template will only be generated as a
PDF and cannot be edited by the user. All quote templates can be edited in the
normal way in Settings and maintenance.
You can customise your own templates for quotes and order confirmations.
Using fields (mergefields) in Word, you can insert quote information in the
template. Combined with the template variables which you use to retrieve
customer data and other information, you can create exactly the quote or order
confirmation you want. SuperOffice CRM is supplied with a number of standard
templates that you can use as they are or adapt to suit your needs.
Note: This requires the Sales User licence.
The mergefields with the quote details (lines, prices, product names, etc.) are
normally placed in a separate template document separated from the quote
document. The quote document is the document/covering letter which the sales
person creates (the Quote section tab in the Sales screen). The quote is
generated as a PDF file in which the quote details are merged into the quote
document and attached to the e-mail that is sent to the customer.
• If you use both the tender document and the quote details, there are
two options:
• If the "QuoteDetails" mergefield is present in the quote document,
the quote details will be inserted where the field is located.
• If the "QuoteDetails" mergefield is NOT present in the quote
document, the quote details will be inserted right at the end of the
document.
• If you only use either the quote document or the quote details, the
quote will be generated as a PDF and attached to the e-mail that is
sent to the customer.
In both cases, one PDF file will be generated and then attached to the e-mail.

## Design
Mergefields are used differently to template variables. Whereas template
variables can be placed anywhere in a template document, mergefields must
follow a structure or a hierarchy. This hierarchy consists of four levels (tables)
which must be placed in the following order ("nesting order"): quote >
alternative > group > line (row)
The "TableStart:xxx" and "TableEnd:xxx" fields define the start and end of
the various table areas (levels):
"TableStart:quote"
"TableStart:alternative"
"TableStart:group"
"TableStart:line"
"TableEnd:line"
"TableEnd:group"
"TableEnd:alternative"
"TableEnd:quote"
For example: Line fields (such as "line/name") can only be placed within the
line table ("TableStart:line""TableEnd:line"), while alternative fields can be
placed within both the alternative table and the underlying tables (group and
line).
You only need to enter each table once in the template. For example: A product
line is shown as one row in the template, but when you generate a quote or an order confirmation in SuperOffice CRM, this row is repeated for each product in
the quote. The same applies to alternatives and groups.
The group table is not obligatory, so you do not need to use this table if you do
not want to group the products.

### Create a sale for testing the template document
In SuperOffice CRM, you should first create a quote with a number of products.
This will make it easier to test the template document you want to create. The
products should be from different product families, so that you can see how
grouping works. The sale should have the same sale type as that which you
link the template document to (see "Link the template document to a sale type"
below). In the quote, you must click Place order, so that the Show
confirmation button becomes available.

### Select the fields to be displayed
Each product consists of many fields containing product data, but by default not
all these fields will be visible. If you want to modify a template document and
insert new fields, you must check that the fields concerned are set as visible in
the Configure product dialog. No value is set for fields which are not defined
as visible in Settings and maintenance. For more details, see "Configure
products" in Help for Settings and maintenance.

### Copy the template to be modified
You are now going to copy an existing template and add it as a new template in
Settings and maintenance. We will use an order confirmation template as a
basis. To do this:
1. Go to the Lists screen and select the Items tab.
2. Click the arrow ( ) and select Document - Template from the List list
box.
3. Double-click the Order confirmation template and click the Edit button.
The template document will open in Word.
4. Save the template document under a new name, and place it somewhere
where you will easily be able to find it again later.
5. Add the template document as described in "Add items to the Document
– Template list" in Help for Settings and maintenance.
6. Give the template document a logical name, such as "Order confirmation
– Grouped".
7. Check the Quote document type option so that the template document
becomes available when you create a quote in SuperOffice CRM. You
must also select the Template for order confirmations type in the list
box.
8. Click Save when you have finished.

### Link the template document to a sale type
We are now going to link the template document to a sale type. Sales with this
sale type will then use this template when you display the confirmation in
SuperOffice CRM. If you have already created a sale in SuperOffice CRM, you
can use this sale type for this sale. To do this:
1. Open the Lists screen.
2. Double-click Sale - Type, Stages, Quote in the Lists tab. The list opens
in the Items tab.
3. Double-click a sale type in the List items overview. The Edit list item
dialog opens.
4. Open the Default values tab > Order confirmation template list, and
select the template document you have created.
5. Click OK.

## Modify the template
We are now going to modify the template document you have prepared. We will
start by inserting some simple fields and an extra column containing product
images in the product list. We will then group the products according to product
family and choose the sorting order.

### Insert fields in Word
Below, we have described two methods for inserting fields in a template
document. The first method is the quickest.
1. Copy an existing field in the template. Make sure you copy the entire
field, including «».
2. Paste the field into the template.
3. Right-click on the field and select Edit fields.
4. In the Field name field under Field properties, enter/paste the field
name you want to insert. Do not include «». For a full list of fields, see
"Annex: Mergefields for quotes" on page 12.
5. Click OK.
OR
1. Place the cursor where you want to insert the field.
2. Go to Insert > Quick Parts > Field. The Field dialog opens.
3. Click in the Field name list under Select a field, and type in "merge".
The MergeField field name is now highlighted in the list.
4. In the Field name field under Field properties, enter/paste the field you
want to insert. Do not include «». For a full list of fields, see "Annex:
Mergefields for quotes" on page 12.
5. Click OK.
Note: You cannot edit the field name (MergeField) directly in the template
document. You must right-click on it and select Edit fields.

### Insert fields in the template document
1. Open the template document from the Document - Template list (as
described above).
2. Insert the following fields in the template document:
Note: It is important that you distinguish between capital and lower case letters
when you type in the field names.
Once you have done this, the template document will look like this (new fields
have been highlighted in the image below):
Field name Location Description
«alternative/name» After the title ("Details") The name of the
alternative (taken
from the quote)
«alternative/numLines» Below the product table (leftaligned on the same row as
the sum total for the
alternative). You should also
enter the label Lines: to the
left of the field.
Number of lines in the
alternative
«Image:line/quoteLineThumbnail» Insert a new column with the
title "Image".
Thumbnail of the
product.
3. Save the template document, but do not close it.

### View the order confirmation in SuperOffice CRM
Before we move on, you can view the order confirmation in SuperOffice CRM
and verify that your changes are displayed correctly. To do this:
1. Open a sale of the same sale type to which the template is linked.
2. Open the Quote tab in the sale and click Open.
3. Click Place order if you have not already done so.
4. Click Show confirmation in the Edit quote dialog. The order confirmation
opens as a PDF file.
5. Check that the order confirmation is displayed correctly:
 All content in the tables must be displayed correctly. Numbers
must not be split over two lines.
 There must be no field names in the document. If there are, you
have entered the wrong field name in the template.
 Are any fields which you have inserted in the template missing?
This may be because data for the field concerned is missing in the
quote/product.
6. Make any modifications you wish to make to the template document and
save it.
7. View the order confirmation again and check that everything is displayed
correctly.

### Grouping and sorting of products
We are now going to do the following:
• Sort the products by product name.
• Group the products in the template document by product family. A
product family could for example be "hardware", "software" or
"accessory".
• Enter a sum total for the products in each group, but retain the sum
total for the alternative that already exists in the template document.
Specify sort order
By default, the products are displayed in the same order (ranking) as in the
quote. However, you can use "OrderBy:" to choose a different sorting order for
the products. "OrderBy:name" sorts the products alphabetically by product
name, while "OrderBy:vatInfo" sorts the products according to VAT status.
• Insert the "OrderBy:name" field somewhere in the template
document.
All the products will now be sorted by product name within each alternative.
They will also be sorted within each group after the grouping area has been
defined (see below).
Specify grouping area
The group must start with "TableStart:group" and end with
"TableEnd:group".
• Insert the "TableStart:group" anywhere in front of "TableStart:line",
e.g. immediately after the name of the alternative.
• Insert the "TableEnd:group" field after "TableEnd:line", e.g.
immediately after the table containing the product fields.
See the screen under "Insert group field" on page 9.
Specify the grouping key
You must also add a field which indicates what you want to group by
("GroupBy:"). In our case, we are going to group according to product family.
You can of course group using a different criterion, such as product category or
an extra field that you have defined yourself. It is possible to group all fields at
line level (i.e. all data that is linked to the products).
• Insert the "GroupBy:productFamilyKey" field somewhere in the
template document.
You can place this field anywhere. It will not be shown in the order actual
confirmation. You can only specify one grouping key.
Insert group field
In the group (i.e. between "TableStart:group" and "TableEnd:group"), you
can add fields which are group-specific. For a full list of fields, see "Annex:
Mergefields for quotes" on page 12.
Tip: Move the table with the sum total for the alternative (including the total
number of lines) down a few lines, so that you have room to insert the group
fields. See the screen below.
1. Insert the following fields:
Field name Location Description
«group/groupField» Between the title and the table
containing the products. Give the
field a header style.
The title of the group (the
name of the field by which the
products are grouped).
«group/sumtotalPrice» At the bottom of the column with
prices.
Sum total for the entire group.
«group/groupField»: In the cell to the left of the sum
total for the entire group. You
The title of the group (the
name of the field by which the
Page 9
SuperOffice CRM – Quote templates
should also type in the label
Sum to the left of the field.
products are grouped).
Once you have done this, the template document will look like this (new fields
have been highlighted in the image below):
2. Save the template document and display it in SuperOffice CRM, as
described above.

## Customisation options
We have summarised below a number of customisation options you can use in
the template documents for quotes.

### Formatting
You can use the formatting options in Word to customise the way in which
fields are displayed in the template documents.
Below, you will see an example of a summary of groups and prices in a quote,
including the sum total for the entire alternative (the quote). In this example, we
have used tabs to place the fields.
Template document
Generated quote

### Numbers
Number fields (e.g. "line/totalPrice") can be formatted with the required
number of decimal places. "line/totalPrice:2" shows a number to two decimal
places. You can also specify five decimal places. If no formatting is specified,
the default value for the selected language will be used.

### Date/time
Date fields (e.g. "quote/sent") can be specified with different date formats. For
example, you can insert the "quote/sent:ShortDate" field if you want a short
date format, or "quote/sent:LongDateTime" if you want to show the full date
and time. The actual format that is displayed will take account of the
language/country ("culture") that has been selected for the quote. If no
formatting is specified, the default value for the selected language will be used.
The following formats are available: ShortDate, ShortTime, ShortDateTime,
LongDate, LongTime and LongDateTime.

### Settings for language and country ("culture")
When you send a quote or an order confirmation in SuperOffice CRM, you must
also select a language. The template for the relevant language will be selected,
and the date, time and numbers will be shown in the correct format for the
chosen language.
However, date, time and number formats are not always the same for all
countries, even if they use the same language. In these cases, you can create
a special template for the language and country concerned (e.g. "Quote to
Swiss customers"). In the template, you must insert the "Culture:xx-YY", field,
where xx-YY is the language/country code. For example: de-CH is GermanSwitzerland and ar-KW is Arabic-Kuwait. You can place the field anywhere in
the template.
For an overview of language codes, see the MSDN pages
(http://msdn.microsoft.com/enus/library/system.globalization.cultureinfo%28v=vs.80%29.aspx).

**Comment by digitaldiina** [comment]
The PDF is already available on docs at https://docs.superoffice.com/downloads/quote-templates.pdf

Stored in the assets folder.

**Comment by digitaldiina** [comment]
![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/23242792/b98104a7-81a6-435b-baca-fe05124a4e37)
