### ISSUE TITLE
Import page contains bad markdown link.

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/superoffice-docs#712]
See in production:
https://docs.superoffice.com/en/onsite/win-client/learn/import/updating-rules-for-duplicate-handling.html

https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/onsite/win-client/learn/import/updating-rules-for-duplicate-handling.md/#L1

![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/15157161/f59497ec-138c-4822-a220-7919f549be5f)

**Comment by pavlas77** [comment]
Also here:
https://docs.superoffice.com/en/onsite/win-client/learn/import/resetting-rules-for-duplicate-handling.html
