### ISSUE TITLE
Centralize learn screenshots

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#721]
To avoid duplicating screenshots for each translated language, the screenshots inside the en folder must be moved to a shared media folder outside the language specific content.

* Target mapping: docs/media/loc/en
* 1 level sub-folders reflecting top-level folders in en/
* Preserve current filename but update paths.

This allows us to introduce localized screenshots in other languages in the future.

### Discarded alternatives

* Copy images to the language specific content folders but map to the same destination as en media with docfx.json
* Use relative paths pointing from no/ to en/**media/. Involves updating 264 paths in each translated language. However, this has the risk of being overwritten in future translations and will most likely have to be repeated.

**Comment by SuperOfficeDevNet** [comment]
Shouldn't docs/media/en and docs/media/no be enough nesting?
