### ISSUE TITLE
Feedback for Criteria operators

### ISSUE THREAD

**Issue by Wilhelmp52** [SuperOfficeDocs/superoffice-docs#724]
[Enter feedback here]
Period types for operators are a litle bit different in the database then in the documentation:
day to quarter is right, but year has value 6 and halfyear has value 5
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [undefined](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/api/search/find-selection/operators.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Thanks for the feedback @Wilhelmp52! This change in the API wasn't communicated, but now has been verified, and fixed in the Operators page accordingly.  Cheers! 🥇
