### ISSUE TITLE
Move federated auth concept and update links to match data access issue 30

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#76]
Data access issue https://github.com/SuperOfficeDocs/data-access/issues/30 has moved, renamed, and merged files pertaining to online authentication. Need to fix links in this repo going to affected files. PRs should be coordinated.

Also, federated-auth.md should be moved here from data access. To be listed in IM section between _Overview_ and 
_Federated ID and identity providers_

**Comment by SuperOfficeDevNet** [comment]
Done
