### ISSUE TITLE
Remove restricted text from DatabaseTable agent

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#77]
https://community.superoffice.com/documentation/sdk/SO.NetServer.Web.Services/html/Methods_T_SuperOffice_Services88_IDatabaseTableAgent.htm
We said it should no longer be restricted back in 2019...

**Comment by digitaldiina** [comment]
Must fix text in source since changes in Markdown will be overwritten on the next update

**Comment by xt1** [comment]
Fixed in source code Release 10.0.5
