### ISSUE TITLE
Need to post info about maintenance windows in docs

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#79]
Our production environment have some windows where we may upgrade and maintain our system. At these times your may not get access to the tenant and you should handle these so no data is lost.

Maintenance window is Saturday between 20.00  (UTC+1) and Sunday 06.00 (UTC+1).  

There is also a patch window on Thursdays between 22.00 (UTC+1) and Friday 06.00  (UTC+1) and at this time the servers may reboot. 

SuperOffice also upgrade our customers on Tuesdays and Fridays every third week, info regarding this will be given on the login page only. The window here is from 20.00  (UTC+1) and may last until 05:00  (UTC+1). 

Every night between 01.00 (UTC+1) and 03.00 (UTC+1) we recycle the application pools for all customers.

Sign up for updates here: https://status.superoffice.com/

**Comment by SuperOfficeDevNet** [comment]
Ongoing work associated with Issues #75
