### ISSUE TITLE
Brokens Links 

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/superoffice-docs#790]
superoffice-docs/docs/de/search-options/learn/in-navigator.md#L28)Invalid file link:(~/superoffice-docs/docs/de/api/osql/soundx.md).
superoffice-docs/docs/nl/learn/activity/index.md#L25)Invalid file link:(~/superoffice-docs/docs/nl/learn/index.md).
superoffice-docs/docs/no/learn/activity/index.md#L25)Invalid file link:(~/superoffice-docs/docs/no/learn/index.md).
superoffice-docs/docs/sv/search-options/learn/in-navigator.md#L28)Invalid file link:(~/superoffice-docs/docs/sv/api/osql/soundx.md).
superoffice-docs/docs/en/learn/activity/index.md#L25)Invalid file link:(~/superoffice-docs/docs/en/learn/index.md).

superoffice-docs/docs/nl/learn/index.yml#L0)Invalid file link:(~/superoffice-docs/docs/nl/learn/compose.md).
superoffice-docs/docs/nl/learn/index.yml#L0)Invalid file link:(~/superoffice-docs/en/document/templates/variables/index.md).
superoffice-docs/docs/no/learn/index.yml#L0)Invalid file link:(~/superoffice-docs/docs/no/learn/compose.md).      
superoffice-docs/docs/no/learn/index.yml#L0)Invalid file link:(~/superoffice-docs/en/document/templates/variables/index.md).
superoffice-docs/docs/sv/learn/index.yml#L0)Invalid file link:(~/superoffice-docs/docs/sv/learn/compose.md).      
superoffice-docs/docs/sv/learn/index.yml#L0)Invalid file link:(~/superoffice-docs/en/document/templates/variables/index.md).
superoffice-docs/docs/da/learn/index.yml#L0)Invalid file link:(~/superoffice-docs/docs/da/learn/compose.md).      
superoffice-docs/docs/da/learn/index.yml#L0)Invalid file link:(~/superoffice-docs/en/document/templates/variables/index.md).
superoffice-docs/docs/de/learn/index.yml#L0)Invalid file link:(~/superoffice-docs/docs/de/learn/compose.md).      
superoffice-docs/docs/de/learn/index.yml#L0)Invalid file link:(~/superoffice-docs/en/document/templates/variables/index.md).
superoffice-docs/docs/da/learn/activity/index.md#L25)Invalid file link:(~/superoffice-docs/docs/da/learn/index.md).
superoffice-docs/docs/de/learn/activity/index.md#L25)Invalid file link:(~/superoffice-docs/docs/de/learn/index.md).
superoffice-docs/docs/nl/search-options/learn/in-navigator.md#L28)Invalid file link:(~/superoffice-docs/docs/nl/api/osql/soundx.md).
superoffice-docs/docs/en/api/entities/activity-links.md#L21)Invalid file link:(~/superoffice-docs/docs/en/sale/saint/entity/media/sale-apt-link.png).
superoffice-docs/docs/sv/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md)Uid(v1TicketAgent_ClearNotify) has already been defined in superoffice-docs/docs/da/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md.
superoffice-docs/docs/sv/api/reference/soap/Services88/Ticket/ClearNotify.md#L14)Invalid file link:(~/superoffice-docs/docs/sv/api/reference/soap/Services88/Services88-Ticket.md).
superoffice-docs/docs/sv/api/reference/soap/Services88/Ticket/ClearNotify.md#L16)Invalid file link:(~/superoffice-docs/docs/sv/api/reference/soap/Services88/SoPrincipal/index.md).
superoffice-docs/docs/sv/api/reference/soap/Services88/Ticket/ClearNotify.md)Uid(Services88-Ticket-ClearNotify) has already been defined in superoffice-docs/docs/da/api/reference/soap/Services88/Ticket/ClearNotify.md.
superoffice-docs/docs/da/search-options/learn/in-navigator.md#L28)Invalid file link:(~/superoffice-docs/docs/da/api/osql/soundx.md).
superoffice-docs/docs/no/api/reference/soap/Services88/Ticket/ClearNotify.md#L18)Invalid file link:(~/superoffice-docs/docs/no/api/reference/soap/Services88/Services88-Ticket.md).
superoffice-docs/docs/no/api/reference/soap/Services88/Ticket/ClearNotify.md#L20)Invalid file link:(~/superoffice-docs/docs/no/api/reference/soap/Services88/SoPrincipal/index.md).
superoffice-docs/docs/en/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md)Uid(v1TicketAgent_ClearNotify) has already been defined in superoffice-docs/docs/no/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md.
superoffice-docs/docs/en/api/reference/soap/Services88/Ticket/ClearNotify.md)Uid(Services88-Ticket-ClearNotify) has already been defined in superoffice-docs/docs/da/api/reference/soap/Services88/Ticket/ClearNotify.md.
superoffice-docs/docs/de/search-options/learn/in-navigator.md#L28)Invalid file link:(~/superoffice-docs/docs/de/api/osql/soundx.md).
superoffice-docs/docs/nl/learn/activity/index.md#L25)Invalid file link:(~/superoffice-docs/docs/nl/learn/index.md).
superoffice-docs/docs/no/learn/activity/index.md#L25)Invalid file link:(~/superoffice-docs/docs/no/learn/index.md).
superoffice-docs/docs/sv/search-options/learn/in-navigator.md#L28)Invalid file link:(~/superoffice-docs/docs/sv/api/osql/soundx.md).
superoffice-docs/docs/en/learn/activity/index.md#L25)Invalid file link:(~/superoffice-docs/docs/en/learn/index.md).
superoffice-docs/docs/nl/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md)Uid(v1TicketAgent_ClearNotify) has already been defined in superoffice-docs/docs/da/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md.
superoffice-docs/docs/nl/api/reference/soap/Services88/Ticket/ClearNotify.md#L14)Invalid file link:(~/superoffice-docs/docs/nl/api/reference/soap/Services88/Services88-Ticket.md).
superoffice-docs/docs/nl/api/reference/soap/Services88/Ticket/ClearNotify.md#L16)Invalid file link:(~/superoffice-docs/docs/nl/api/reference/soap/Services88/SoPrincipal/index.md).
superoffice-docs/docs/nl/api/reference/soap/Services88/Ticket/ClearNotify.md)Uid(Services88-Ticket-ClearNotify) has already been defined in superoffice-docs/docs/da/api/reference/soap/Services88/Ticket/ClearNotify.md.
superoffice-docs/docs/sv/learn/activity/index.md#L25)Invalid file link:(~/superoffice-docs/docs/sv/learn/index.md).
superoffice-docs/docs/en/api/search/selection/dynamic-selections.md#L58)Invalid file link:(~/superoffice-docs/docs/en/sale/saint/counters.md).
superoffice-docs/docs/en/api/authentication/online/validate-security-tokens.md#L99)Invalid file link:(~/superoffice-docs/docs/assets/downloads/api/index.md).
superoffice-docs/docs/en/api/authentication/online/validate-security-tokens.md#L429)Invalid file link:(~/superoffice-docs/docs/assets/downloads/api/index.md).
superoffice-docs/docs/en/api/authentication/online/auth-application/get-system-user-ticket.md#L65)Invalid file link:(~/assets/downloads/api/partnersystemuserservice.zip).
superoffice-docs/docs/da/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md)Uid(v1TicketAgent_ClearNotify) has already been defined in superoffice-docs/docs/de/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md.
docs/da/api/reference/soap/Services88/Ticket/ClearNotify.md)Uid(Services88-Ticket-ClearNotify) has already been defined in superoffice-docs/docs/de/api/reference/soap/Services88/Ticket/ClearNotify.md.
superoffice-docs/docs/de/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md)Uid(v1TicketAgent_ClearNotify) has already been defined in superoffice-docs/docs/en/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md.
superoffice-docs/docs/de/api/reference/soap/Services88/Ticket/ClearNotify.md#L14)Invalid file link:(~/superoffice-docs/docs/de/api/reference/soap/Services88/Services88-Ticket.md).
superoffice-docs/docs/de/api/reference/soap/Services88/Ticket/ClearNotify.md#L16)Invalid file link:(~/superoffice-docs/docs/de/api/reference/soap/Services88/SoPrincipal/index.md).
superoffice-docs/docs/de/api/reference/soap/Services88/Ticket/ClearNotify.md)Uid(Services88-Ticket-ClearNotify) has already been defined in superoffice-docs/docs/no/api/reference/soap/Services88/Ticket/ClearNotify.md.

superoffice-docs/docs/de/marketing/mailing/learn/create/add-unsubscribe-link.md#L64)Invalid link: '<a href="superoffice-docs/docs/de/marketing/tracked-links/learn/define-link-actions.md#interests">Link, der das betroffene Interesse von den Empfängern löscht</a>'. The file superoffice-docs/docs/de/marketing/tracked-links/learn/define-link-actions.md doesn't contain a bookmark named 'interests'.

**Comment by digitaldiina** [comment]
**Revised list, sorted by path and `¨/` omitted**

- docs/da/api/reference/soap/Services88/Ticket/ClearNotify.md)Uid(Services88-Ticket-ClearNotify) has already been defined in superoffice-docs/docs/de/api/reference/soap/Services88/Ticket/ClearNotify.md.
- superoffice-docs/docs/da/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md)Uid(v1TicketAgent_ClearNotify) has already been defined in superoffice-docs/docs/de/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md.
- superoffice-docs/docs/da/learn/activity/index.md#L25)Invalid file link:(superoffice-docs/docs/da/learn/index.md).
- superoffice-docs/docs/da/learn/index.yml#L0)Invalid file link:(superoffice-docs/docs/da/learn/compose.md).
- superoffice-docs/docs/da/learn/index.yml#L0)Invalid file link:(superoffice-docs/en/document/templates/variables/index.md).
- superoffice-docs/docs/da/search-options/learn/in-navigator.md#L28)Invalid file link:(superoffice-docs/docs/da/api/osql/soundx.md).
- superoffice-docs/docs/de/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md)Uid(v1TicketAgent_ClearNotify) has already been defined in superoffice-docs/docs/en/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md.
- superoffice-docs/docs/de/api/reference/soap/Services88/Ticket/ClearNotify.md#L14)Invalid file link:(superoffice-docs/docs/de/api/reference/soap/Services88/Services88-Ticket.md).
- superoffice-docs/docs/de/api/reference/soap/Services88/Ticket/ClearNotify.md#L16)Invalid file link:(superoffice-docs/docs/de/api/reference/soap/Services88/SoPrincipal/index.md).
- superoffice-docs/docs/de/api/reference/soap/Services88/Ticket/ClearNotify.md)Uid(Services88-Ticket-ClearNotify) has already been defined in superoffice-docs/docs/no/api/reference/soap/Services88/Ticket/ClearNotify.md.
- superoffice-docs/docs/de/learn/activity/index.md#L25)Invalid file link:(superoffice-docs/docs/de/learn/index.md).
- superoffice-docs/docs/de/learn/index.yml#L0)Invalid file link:(superoffice-docs/docs/de/learn/compose.md).
- superoffice-docs/docs/de/learn/index.yml#L0)Invalid file link:(superoffice-docs/en/document/templates/variables/index.md).
- superoffice-docs/docs/de/marketing/mailing/learn/create/add-unsubscribe-link.md#L64)Invalid link: '<a href="superoffice-docs/docs/de/marketing/tracked-links/learn/define-link-actions.md#interests">Link, der das betroffene Interesse von den Empfängern löscht</a>'. The file superoffice-docs/docs/de/marketing/tracked-links/learn/define-link-actions.md doesn't contain a bookmark named 'interests'.
- superoffice-docs/docs/de/search-options/learn/in-navigator.md#L28)Invalid file link:(superoffice-docs/docs/de/api/osql/soundx.md).
- superoffice-docs/docs/en/api/authentication/online/auth-application/get-system-user-ticket.md#L65)Invalid file link:(assets/downloads/api/partnersystemuserservice.zip).
- superoffice-docs/docs/en/api/authentication/online/validate-security-tokens.md#L429)Invalid file link:(superoffice-docs/docs/assets/downloads/api/index.md).
- superoffice-docs/docs/en/api/authentication/online/validate-security-tokens.md#L99)Invalid file link:(superoffice-docs/docs/assets/downloads/api/index.md).
- superoffice-docs/docs/en/api/entities/activity-links.md#L21)Invalid file link:(superoffice-docs/docs/en/sale/saint/entity/media/sale-apt-link.png).
- superoffice-docs/docs/en/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md)Uid(v1TicketAgent_ClearNotify) has already been defined in superoffice-docs/docs/no/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md.
- superoffice-docs/docs/en/api/reference/soap/Services88/Ticket/ClearNotify.md)Uid(Services88-Ticket-ClearNotify) has already been defined in superoffice-docs/docs/da/api/reference/soap/Services88/Ticket/ClearNotify.md.
- superoffice-docs/docs/en/api/search/selection/dynamic-selections.md#L58)Invalid file link:(superoffice-docs/docs/en/sale/saint/counters.md).
- superoffice-docs/docs/en/learn/activity/index.md#L25)Invalid file link:(superoffice-docs/docs/en/learn/index.md).
- superoffice-docs/docs/nl/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md)Uid(v1TicketAgent_ClearNotify) has already been defined in superoffice-docs/docs/da/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md.
- superoffice-docs/docs/nl/api/reference/soap/Services88/Ticket/ClearNotify.md#L14)Invalid file link:(superoffice-docs/docs/nl/api/reference/soap/Services88/Services88-Ticket.md).
- superoffice-docs/docs/nl/api/reference/soap/Services88/Ticket/ClearNotify.md#L16)Invalid file link:(superoffice-docs/docs/nl/api/reference/soap/Services88/SoPrincipal/index.md).
- superoffice-docs/docs/nl/api/reference/soap/Services88/Ticket/ClearNotify.md)Uid(Services88-Ticket-ClearNotify) has already been defined in superoffice-docs/docs/da/api/reference/soap/Services88/Ticket/ClearNotify.md.
- superoffice-docs/docs/nl/learn/activity/index.md#L25)Invalid file link:(superoffice-docs/docs/nl/learn/index.md).
- superoffice-docs/docs/nl/learn/index.yml#L0)Invalid file link:(superoffice-docs/docs/nl/learn/compose.md).
- superoffice-docs/docs/nl/learn/index.yml#L0)Invalid file link:(superoffice-docs/en/document/templates/variables/index.md).
- superoffice-docs/docs/nl/search-options/learn/in-navigator.md#L28)Invalid file link:(superoffice-docs/docs/nl/api/osql/soundx.md).
- superoffice-docs/docs/no/api/reference/soap/Services88/Ticket/ClearNotify.md#L18)Invalid file link:(superoffice-docs/docs/no/api/reference/soap/Services88/Services88-Ticket.md).
- superoffice-docs/docs/no/api/reference/soap/Services88/Ticket/ClearNotify.md#L20)Invalid file link:(superoffice-docs/docs/no/api/reference/soap/Services88/SoPrincipal/index.md).
- superoffice-docs/docs/no/learn/activity/index.md#L25)Invalid file link:(superoffice-docs/docs/no/learn/index.md).
- superoffice-docs/docs/no/learn/index.yml#L0)Invalid file link:(superoffice-docs/docs/no/learn/compose.md).
- superoffice-docs/docs/no/learn/index.yml#L0)Invalid file link:(superoffice-docs/en/document/templates/variables/index.md).
- superoffice-docs/docs/sv/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md)Uid(v1TicketAgent_ClearNotify) has already been defined in superoffice-docs/docs/da/api/reference/restful/agent/Ticket_Agent/v1TicketAgent_ClearNotify.md.
- superoffice-docs/docs/sv/api/reference/soap/Services88/Ticket/ClearNotify.md#L14)Invalid file link:(superoffice-docs/docs/sv/api/reference/soap/Services88/Services88-Ticket.md).
- superoffice-docs/docs/sv/api/reference/soap/Services88/Ticket/ClearNotify.md#L16)Invalid file link:(superoffice-docs/docs/sv/api/reference/soap/Services88/SoPrincipal/index.md).
- superoffice-docs/docs/sv/api/reference/soap/Services88/Ticket/ClearNotify.md)Uid(Services88-Ticket-ClearNotify) has already been defined in superoffice-docs/docs/da/api/reference/soap/Services88/Ticket/ClearNotify.md.
- superoffice-docs/docs/sv/learn/activity/index.md#L25)Invalid file link:(superoffice-docs/docs/sv/learn/index.md).
- superoffice-docs/docs/sv/learn/index.yml#L0)Invalid file link:(superoffice-docs/docs/sv/learn/compose.md).
- superoffice-docs/docs/sv/learn/index.yml#L0)Invalid file link:(superoffice-docs/en/document/templates/variables/index.md).
- superoffice-docs/docs/sv/search-options/learn/in-navigator.md#L28)Invalid file link:(superoffice-docs/docs/sv/api/osql/soundx.md).
