### ISSUE TITLE
Create vendor-specific landing pages for video meetings

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#80]
Some providers require documentation to be grouped a certain way. Challenge: comply with minimal duplication to stay SEO friendly and also contributor friendly

Additional tasks:

- Add new section "How to remove video-meetings configuration for users" (general)
- Add new section "Troubleshooting and errors" (general)
- Add new section "Remove Access for Video Meeting App in Google"

**Comment by SuperOfficeDevNet** [comment]
Done.

**Comment by digitaldiina** [comment]
New requirements were discussed today with E. Lebiko and RnD Services. We need to do another restructuring pass.

**Comment by pavlas77** [comment]
Went over the pages, now we need to get Frode and Erik L to reviwe trhem.
