### ISSUE TITLE
Learn: Need of Anchors on specific pages that has F1 connection from SuperOffice UI.

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#804]
After merge of a lot of pages, there is a need of new anchors to make the F1 functionality in SuperOffice to work smoothly.

Chapter where a new anchor is needed:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kirsti/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kirsti/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

# | Line User/Admin | Dispatcher url | Need anchor
-- | -- | -- | --
69 | u69 | search-options/selection/learn/update/add-remove-members-static.html |  
70 | u70 | search-options/selection/learn/update/add-remove-members-static.html#remove-members-using-search-criteria | Yes
74 | u74 | search-options/selection/learn/howto/export.html#export-to-file | Yes
83 | u83 | reports/learn/labels/index.html#add-label-format | Yes
111 | u111 | search-options/learn/find-screen.html#example-1-search-for-profitable-customers | Yes
112 | u112 | search-options/learn/find-screen.html#example-4-search-for-projects-you-have-participated-in-during-the-last-year | Yes
115 | u115 | search-options/learn/find-screen.html#example-3-search-for-sold-sales | Yes
119 | u119 | search-options/learn/find-screen.html#example-2-search-for-customers-in-denmark-who-you-are-responsible-for | Yes
120 | u120 | search-options/learn/find-screen.html#example-4-search-for-projects-you-have-participated-in-during-the-last-year | Yes
123 | u123 | search-options/learn/find-screen.html#example-3-search-for-sold-sales | Yes
126 | u126 | search-options/learn/find-screen.html#work-with-search-results | Yes
153 | u153 | learn/section-tabs/index.html#sort-lists | Yes
159 | u159 | learn/section-tabs/index.html#sort-lists | Yes
167 | u167 | quote/learn/create.html#is-the-select-erp-connection-dialog-displayed | Yes
199 | u199 | marketing/learn/editor.html#editor-old | Yes
201 | u201 | marketing/learn/editor.html#editor-old | Yes
209 | u209 | marketing/learn/editor.html#editor-old | Yes
217 | u217 | marketing/learn/editor.html#editor-old | Yes
268 | a6 | admin/preferences/learn/update-preferences.html#edit-preference-setting | Yes
319 | a57 | admin/user-management/learn/screen/index.html#other-users-onsite | Yes
320 | a58 | admin/user-management/learn/screen/index.html#our-companies | Yes
360 | a98 | admin/user-management/learn/screen/index.html#the-associate-list | Yes

</body>

</html>

## The list in one line:
search-options/selection/learn/update/add-remove-members-static.html
search-options/selection/learn/update/add-remove-members-static.html#remove-members-using-search-criteria
search-options/selection/learn/howto/export.html#export-to-file
reports/learn/labels/index.html#add-label-format
search-options/learn/find-screen.html#example-1-search-for-profitable-customers
search-options/learn/find-screen.html#example-4-search-for-projects-you-have-participated-in-during-the-last-year
search-options/learn/find-screen.html#example-3-search-for-sold-sales
search-options/learn/find-screen.html#example-2-search-for-customers-in-denmark-who-you-are-responsible-for
search-options/learn/find-screen.html#example-4-search-for-projects-you-have-participated-in-during-the-last-year
search-options/learn/find-screen.html#example-3-search-for-sold-sales
search-options/learn/find-screen.html#work-with-search-results
learn/section-tabs/index.html#sort-lists
learn/section-tabs/index.html#sort-lists
quote/learn/create.html#is-the-select-erp-connection-dialog-displayed
marketing/learn/editor.html#editor-old
marketing/learn/editor.html#editor-old
marketing/learn/editor.html#editor-old
marketing/learn/editor.html#editor-old
admin/preferences/learn/update-preferences.html#edit-preference-setting
admin/user-management/learn/screen/index.html#other-users-onsite
admin/user-management/learn/screen/index.html#our-companies
admin/user-management/learn/screen/index.html#the-associate-list

**Comment by digitaldiina** [comment]
* admin/preferences/learn/update-preferences.md #edit
* admin/user-management/learn/screen/index.md #associates, #other-users, #our-companies
* learn/section-tabs/index.md #sort
* marketing/learn/editor.md #old
* quote/learn/create.md #erp
* reports/learn/labels/index.md #add-format
* search-options/selection/learn/howto/export.md #to-file
* search-options/selection/learn/update/add-remove-members-static.md #remove

Please use the existing anchors in find-screen.md: results, ex1, ex2, ex3, ex4, ex5

Added anchor to editor.md. However, that section is only 1 screenshot + 1 sentence linking to [10.1 help](https://help.superoffice.com/Documentation/Help/EN/CRM/UserHelp/index.htm#t=Mailing%2FHelptopics%2Foldeditor%2FStep_3__Content_-_Formatted_e-mail.htm). Think the dispatcher should link directly to that page rather than ask a confused user to click two links.

**Comment by kirstiaa** [comment]
@digitaldiina 
As for the marketing and old editor:

Would it be possible to add anchor on this url?
https://docs.superoffice.com/en/marketing/learn/editor.html#two-different-editors

I think it's important that the user will get the correct help. By confusing them with the info about Drag&Drop editor, they might not scroll down to see the relevant info + the link to help.superoffice.com and the old editor help.

**Comment by digitaldiina** [comment]
Yes, it's possible. But please clarify. Do you want to replace the anchor #old that sends them directly to the initially requested section, or do you want a second anchor in the same file? Linking to #two-different-editors if they should go to #old seems more confusing, but I might have misunderstood the use case.

**Comment by kirstiaa** [comment]
There are 4 places in the UI (so-protocol) where they ask for a help url:
- emarketing.www.spm.document.step3.oldeditor
- emarketing.www.spm.email.step3.oldeditor
- emarketing.www.spm.listTemplates.oldeditor
- emarketing.www.spm.form.step3.oldeditor

As you can see, all these shows the Old editor in the UI.
For this we need a help to give them a good solution when the New editor is not what they need.

So, if you think it's better to anchor the chapter above, we can do that. 

It's due to the comment you had, @digitaldiina , I asked yesterday about a different way to anchor this:

< Added anchor to editor.md. However, that section is only 1 screenshot + 1 sentence linking to [10.1 help](https://help.superoffice.com/Documentation/Help/EN/CRM/UserHelp/index.htm#t=Mailing%2FHelptopics%2Foldeditor%2FStep_3__Content_-_Formatted_e-mail.htm). Think the dispatcher should link directly to that page rather than ask a confused user to click two links.

So maybe I misunderstood what you asked/said...?

**Comment by digitaldiina** [comment]
My suggestion was that instead of linking to editor.md#old on docs, the dispatcher should link directly to the page on help.superoffice.docs (like we do for Service). Sorry if that wasn't clear.

If that is not technically possible, editor.md#old is the best (most precise) option.
