### ISSUE TITLE
Feedback for Force resync in prod

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#844]
There's a comment in the middle of the list here restarting it and breaking numbering in the list
![image](https://github.com/SuperOfficeDocs/feedback/assets/22498774/db1800ab-476c-449e-b4f8-39f961566fa9)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [force_mirroring_resync](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/mirroring/force-resync.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
@MargretheR ... the way to fix this is just edit it the page and give the use explicit list numbering...
