### ISSUE TITLE
Update SOFO for Onsite

### ISSUE THREAD

**Issue by pavlas77** [SuperOfficeDocs/superoffice-docs#852]
Since the last release of SuperOffice for Outlook we do support also Onsite installations. Update this on Docs:

- https://docs.superoffice.com/en/online/system-requirements.html
- https://docs.superoffice.com/en/email/superoffice-for-outlook/index.html

**Comment by digitaldiina** [comment]
@pavlas77 is this solved by PRs #855 and #851?

**Comment by pavlas77** [comment]
@digitaldiina Bare partially, it needs updates on more pages. Frode fixed only one. Please merge what he has done and I'll fix the others. Please keep this issue open.
