### ISSUE TITLE
Feedback for Requirements

### ISSUE THREAD

**Issue by samuelholmstroem** [SuperOfficeDocs/superoffice-docs#854]
Hi!
I see that we have not updated the "online only" info.
Since SOFO is now working for onsite customers on version SuperOffice CRM Onsite  10.0.1 or newer

I was told that I can make a change or a "fork" of the github post myself but I never worked with github before so if you give me a call when you will update and show me how to this, then I can start doing it in the correct way!

// Samuel Holmström

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [superoffice_for_outlook_requirements](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/email/superoffice-for-outlook/requirements.md/#L1)

**Comment by pavlas77** [comment]
Hi @samuelholmstroem this is already fixed in the Online system requirements and I'll fix it on the other places soon, so it is work in progress. You just will not see it untill the next Docs build.
