### ISSUE TITLE
Feedback for Run website on IIS localhost

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#86]
Screenshot refers to media/image014.png, which seems to be an HTML page save as PNG.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [run_website_on_iis_localhost](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/apps/getting-started/run-website-on-iis-localhost.md/#L1)

**Comment by digitaldiina** [comment]
Screenshot of the updated page built on localhost

![image](https://user-images.githubusercontent.com/23242792/123919132-e7a20e80-d984-11eb-93ef-96308de52045.png)
