### ISSUE TITLE
Feedback for Drag and drop editor

### ISSUE THREAD

**Issue by filipjnorman** [SuperOfficeDocs/superoffice-docs#864]
[Enter feedback here]

Miss the element for video in this drop and drag editor
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-editor](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/marketing/learn/editor.md/#L1)

**Comment by digitaldiina** [comment]
Retaking screenshots as part of #1055
