### ISSUE TITLE
[Bug]: Search broken due to CSP policy

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which content section have you found a bug in?

Learn

### What kind of bug is it?

Other

### What happened?

The search is broken because of a (new?) CSP policy that blocks the customsearch javascript from being loaded.

See no search bar:

![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/40491305/a979f45b-57a2-43ae-b1b8-ccd582a7eaf3)

Dev console:

![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/40491305/58393633-b8cc-44df-910b-020f7661dce7)

**Comment by SuperOfficeDevNet** [comment]
Thanks David! 💯 Fixed.
