### ISSUE TITLE
Feedback for Application environment

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#88]
I would expect a download link to the certificates files for the different environments on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [app_envir](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/apps/getting-started/app-envir.md/#L1)

**Comment by digitaldiina** [comment]
Thanks for the feedback, @acdavidh ! We'll add a download link to the ZIP file containing all the certificates.
