### ISSUE TITLE
Feedback for Service 10.2.8 update

### ISSUE THREAD

**Issue by KarolinaPestininkaite** [SuperOfficeDocs/superoffice-docs#950]
Screenshot used in this part is misleading for the customers: 
![image](https://github.com/SuperOfficeDocs/feedback/assets/151756873/21fc1b2d-3a8f-47b2-918a-f86a9af74bc6)
 The variables used in the screenshot are not possible to use in request signature. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [news-service-10.2.8](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/release-notes/10.2/service/10.2.8-update.md/#L1)

**Comment by kirstiaa** [comment]
![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/102585577/4f7d2407-98cd-4a66-b35c-053afba4d8f9)
Add service variables to the screenshot and upload to github

**Comment by digitaldiina** [comment]
@kirstiaa The page in question is about system signature. Please use the same dialog as in the original. Consider resizing the image to show less white-space. That will make the text in the screenshot easier to read.

**Comment by kirstiaa** [comment]
@digitaldiina Yes, the screenshot will not look like above, just an image gotten from Karolina 😉 to show the service variables used in the dialog.

I will update the image when 10.2.11 release notes is written.
