### ISSUE TITLE
Update user section for 1.17 - add "co-workers" as users

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#956]
From 1.17 we will open up for adding users in developer portal. Basic rule, you can only add SuperId users from our production environment who are users of a tenant you both share.
User A have access to tenant 1 and 2
User B have access to tenant 2 and 3
User C have access to tenant 3

User A can add User B
User B can add User A and C
User C can add User B

Adding and removing users will also notify the new user by email (request), "you have been added to partner xxx" / "you have been removed from partner xxx"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [dp-add-user](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/developer-portal/partner/add-user.md/#L1)

**Comment by digitaldiina** [comment]
see #1044 #1069
