### ISSUE TITLE
Feedback for Check application performance

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#957]
Need more information about what we count as a record for the API Performance columns Count vs Record Count 
![image](https://github.com/SuperOfficeDocs/feedback/assets/22498774/ea961827-eb9e-430e-a2c2-aa04cb8bfe41)
One entity = one record, meaning one company, contact, project, sale with all corresponding rows like the address, phones, list items linked to it and so on.
Asking for a list however, will count each list item as one database record. So calling the country list will count each individual country in the list as one record.
Caching information that is rarely changes will have an impact, like all lists available in the settings and maintenance client..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [dp-metric-performance](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/developer-portal/analytics/metrics-performance.md/#L1)

**Comment by digitaldiina** [comment]
Reuse text from developer-portal/analytics/metered-services.
