### ISSUE TITLE
Feedback for CRMScript best practices

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#958]
Is this script supposed to run as a schedule task (add in link to help/learn)? Consider how often you really need to run it and which other tasks are also set up to run. Having a script run every minute is not recommended. 
Also check back later, did you add in a schedule task that is no longer needed? Could the schedule be changes? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [crmscript_best_practice](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/automation/crmscript/code-quality/best-practices.md/#L1)

**Comment by digitaldiina** [comment]
Added section below API usage.
![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/23242792/f6eb8a45-0a5e-458d-865b-0a32b8bd7bac)
