### ISSUE TITLE
Update logging section for 10.2.X Onsite

### ISSUE THREAD

**Issue by pavlas77** [SuperOfficeDocs/superoffice-docs#967]
Update logging section for 10.2.X Onsite. Add info that now the logging levels are set by json file and not by AppProductConfig

https://docs.superoffice.com/en/onsite/debug/web-client.html
https://docs.superoffice.com/en/onsite/debug/win-client.html

https://superofficenorge.sharepoint.com/:p:/r/sites/VilniusCXC/operational/_layouts/15/Doc.aspx?sourcedoc=%7B2BF4F194-3430-4A4E-BC68-D6FF63D49D36%7D&file=Netserver10.2.X.pptx&action=edit&mobileredirect=true&DefaultItemOpen=1

**Comment by digitaldiina** [comment]
@pavlas77 can you look at this issue? With the first 10.3 onsite release around the corner, we should wrap up 10.2. It sounds like a small update, but I don't have access to the linked resource.
