### ISSUE TITLE
Changes to List - Follow-up type

### ISSUE THREAD

**Issue by Tonelofsgaard** [SuperOfficeDocs/superoffice-docs#985]
Her kommer det noen endringer - forhåpentligvis klare til neste release:
![Screenshot 2023-12-12 at 13 09 28](https://github.com/SuperOfficeDocs/feedback/assets/148855470/620dce07-4151-4c81-aa9a-9c21d4b9eb4c)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [diary-howto](https://github.com/SuperOfficeDocs/superoffice-docs/blob/827-new-follow-up-dialog/docs/en/diary/howto/index.md/#L1)

**Comment by digitaldiina** [comment]
See also #879

**Comment by digitaldiina** [comment]
We currently don't state the values explicit nor do we show a screenshot. The linked page includes the following list:
![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/23242792/cc3d231e-d804-49a7-ad84-7695acfce80f)

Nothing to change.
