### ISSUE TITLE
Script tracing limits and notifications

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#991]
Needs to be updated with this new feature: https://community.superoffice.com/no/product-releases/bugs-wishes/product-issue/?bid=49609&azure=1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [crmscript_debug_using_trace](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/automation/crmscript/debugging/using-trace.md/#L1)

**Comment by digitaldiina** [comment]
Affects automation/crmscript/learn/tracing too.
